/**
 * m113.coordinator-wire.test.ts — WorkQueueCoordinator wire-in regression tests.
 *
 * SCOPE:
 *  1. LOCAL identity: with no sharedQueue config, a full tick() selects the same
 *     items and writes the same worked-ledger entries as the pre-change path.
 *     Asserts: items chosen == expected ids, ledger written with correct outcome.
 *
 *  2. SHARED two-machine disjoint: two simulated ticks (machineId 'A' and 'B')
 *     over the same backlog claim DISJOINT sets. An item machine-A marked 'empty'
 *     is globally skipped by machine-B.
 *
 * SAFETY / HERMETICITY (mirrors m85 / m106):
 *  - HOME overridden to tmp dir — no real ~/.ashlr state touched.
 *  - runSwarm, runGoal, routeBackend, runAutoMergePass, buildBacklog ALL MOCKED.
 *  - No real agents, subprocesses, or API calls.
 *  - ASHLR_IN_DAEMON / ASHLR_IN_SWARM cleaned up in afterEach.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import type { AshlrConfig, WorkItem } from '../src/core/types.js';
import type { RouteDecision } from '../src/core/fleet/router.js';

// ---------------------------------------------------------------------------
// HOME isolation — before any module import resolves homedir()
// ---------------------------------------------------------------------------

const origHome = process.env.HOME;
const origInDaemon = process.env.ASHLR_IN_DAEMON;
const origInSwarm = process.env.ASHLR_IN_SWARM;

let tmpHome: string;
let tmpRepo: string;

// ---------------------------------------------------------------------------
// Mocks — declared before lazy imports (same pattern as m85 / m106)
// ---------------------------------------------------------------------------

const mockRunSwarm = vi.fn();
vi.mock('../src/core/swarm/runner.js', () => ({
  runSwarm: (...args: unknown[]) => mockRunSwarm(...args),
}));

const mockRunGoal = vi.fn();
vi.mock('../src/core/run/orchestrator.js', () => ({
  runGoal: (...args: unknown[]) => mockRunGoal(...args),
}));

let routeResult: RouteDecision = { backend: 'builtin', tier: 'local', reason: 'test' };
const mockRouteBackend = vi.fn();
vi.mock('../src/core/fleet/router.js', () => ({
  routeBackend: (...args: unknown[]) => mockRouteBackend(...args),
}));

const mockRunAutoMergePass = vi.fn();
vi.mock('../src/core/fleet/automerge-pass.js', () => ({
  runAutoMergePass: (...args: unknown[]) => mockRunAutoMergePass(...args),
}));

let backlogItems: WorkItem[] = [];
const mockBuildBacklog = vi.fn();
vi.mock('../src/core/portfolio/backlog.js', () => ({
  buildBacklog: (...args: unknown[]) => mockBuildBacklog(...args),
}));

const mockLoadConfig = vi.fn();
vi.mock('../src/core/config.js', async () => {
  const real = await vi.importActual<typeof import('../src/core/config.js')>(
    '../src/core/config.js',
  );
  return {
    ...real,
    loadConfig: (...args: unknown[]) => mockLoadConfig(...args),
    defaultConfig: () => ({ version: 1 }),
    saveConfig: vi.fn(),
  };
});

// ---------------------------------------------------------------------------
// Lazy imports — after mocks
// ---------------------------------------------------------------------------

import { tick } from '../src/core/daemon/loop.js';
import { enroll, unenroll, setKill } from '../src/core/sandbox/policy.js';
import { createProposal } from '../src/core/inbox/store.js';
import {
  loadWorkedLedger,
  recordOutcome as localRecord,
} from '../src/core/fleet/worked-ledger.js';
import {
  LocalWorkQueueCoordinator,
  SharedWorkQueueCoordinator,
} from '../src/core/seams/work-queue-coordinator.js';
import { SharedStore } from '../src/core/fleet/shared-store.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeCfg(overrides: Record<string, unknown> = {}): AshlrConfig {
  return {
    version: 1,
    daemon: {
      dailyBudgetUsd: 10.0,
      perTickItems: 6,
      parallel: 6,
      intervalMs: 100,
    },
    ...overrides,
  } as AshlrConfig;
}

function initBareGitDir(dir: string): void {
  fs.mkdirSync(path.join(dir, '.git'), { recursive: true });
  fs.writeFileSync(path.join(dir, '.git', 'HEAD'), 'ref: refs/heads/main\n', 'utf8');
  fs.writeFileSync(
    path.join(dir, '.git', 'config'),
    '[core]\n\trepositoryformatversion = 0\n',
    'utf8',
  );
}

function makeItem(id: string, repo: string, over?: Partial<WorkItem>): WorkItem {
  return {
    id,
    repo,
    source: 'todo',
    title: `Item ${id}`,
    detail: `detail for ${id}`,
    value: 3,
    effort: 3,
    score: 1,
    tags: [],
    ts: new Date().toISOString(),
    ...over,
  };
}

function swarmStub(repo: string) {
  return async () => {
    createProposal({
      repo,
      origin: 'swarm',
      kind: 'patch',
      title: 'Mock swarm proposal',
      summary: 'Generated by mock runSwarm',
      diff: 'diff --git a/x.ts b/x.ts\n',
    });
    return {
      id: `mock-swarm-${Date.now()}`,
      status: 'done',
      goal: 'mock goal',
      result: 'mock result',
      usage: { estCostUsd: 0, totalTokens: 0, steps: 1 },
    };
  };
}

// ---------------------------------------------------------------------------
// beforeEach / afterEach
// ---------------------------------------------------------------------------

beforeEach(() => {
  tmpHome = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m113-home-'));
  tmpRepo = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m113-repo-'));
  process.env.HOME = tmpHome;

  initBareGitDir(tmpRepo);
  fs.writeFileSync(path.join(tmpRepo, 'package.json'), JSON.stringify({ name: 'r' }), 'utf8');

  mockRunSwarm.mockReset();
  mockRunGoal.mockReset();
  mockRouteBackend.mockReset();
  mockRunAutoMergePass.mockReset();
  mockBuildBacklog.mockReset();
  mockLoadConfig.mockReset();

  routeResult = { backend: 'builtin', tier: 'local', reason: 'test' };
  backlogItems = [];

  mockRouteBackend.mockImplementation(() => routeResult);
  mockRunAutoMergePass.mockImplementation(async () => ({ attempted: 0, merged: 0, results: [] }));
  mockBuildBacklog.mockImplementation(async () => ({
    generatedAt: new Date().toISOString(),
    repos: [tmpRepo],
    items: backlogItems,
  }));
  mockRunSwarm.mockImplementation(swarmStub(tmpRepo));
  mockRunGoal.mockImplementation(async () => ({
    id: `mock-run-${Date.now()}`,
    status: 'done',
    usage: { estCostUsd: 0 },
  }));
  mockLoadConfig.mockImplementation(() => makeCfg());

  delete process.env.ASHLR_IN_DAEMON;
  delete process.env.ASHLR_IN_SWARM;
});

afterEach(() => {
  try { unenroll(tmpRepo); } catch { /* ignore */ }
  try { setKill(false); } catch { /* ignore */ }

  fs.rmSync(tmpHome, { recursive: true, force: true });
  fs.rmSync(tmpRepo, { recursive: true, force: true });

  process.env.HOME = origHome;
  if (origInDaemon !== undefined) process.env.ASHLR_IN_DAEMON = origInDaemon;
  else delete process.env.ASHLR_IN_DAEMON;
  if (origInSwarm !== undefined) process.env.ASHLR_IN_SWARM = origInSwarm;
  else delete process.env.ASHLR_IN_SWARM;
});

// ---------------------------------------------------------------------------
// Block 1: LocalWorkQueueCoordinator unit — identical to pre-change behavior
// ---------------------------------------------------------------------------

describe('LocalWorkQueueCoordinator unit', () => {
  it('claimItems returns top-count candidates unchanged', () => {
    const coord = new LocalWorkQueueCoordinator();
    const items = [
      makeItem('a', tmpRepo),
      makeItem('b', tmpRepo),
      makeItem('c', tmpRepo),
    ];
    // Count=2 → first two
    expect(coord.claimItems(items, 2, 'machine-x').map(i => i.id)).toEqual(['a', 'b']);
    // Count=10 → all (no overflow)
    expect(coord.claimItems(items, 10, 'machine-x').map(i => i.id)).toEqual(['a', 'b', 'c']);
    // Count=0 → empty
    expect(coord.claimItems(items, 0, 'machine-x')).toHaveLength(0);
  });

  it('shouldSkip delegates to local recentlyDeclined', () => {
    const coord = new LocalWorkQueueCoordinator();
    // Before any record: not skipped
    expect(coord.shouldSkip('item-z', 6 * 60 * 60 * 1000)).toBe(false);
    // Record an empty outcome via localRecord
    localRecord('item-z', 'empty');
    // Within cooldown window: should skip
    expect(coord.shouldSkip('item-z', 6 * 60 * 60 * 1000)).toBe(true);
    // After cooldown expired: use 0ms window (nowMs - eventMs >= 0, so not < 0 → not skipped)
    expect(coord.shouldSkip('item-z', 0)).toBe(false);
  });

  it('recordOutcome writes to the local worked ledger', () => {
    const coord = new LocalWorkQueueCoordinator();
    coord.recordOutcome('item-q', 'diff', 'machine-x');
    const ledger = loadWorkedLedger();
    const event = ledger.events.find(e => e.itemId === 'item-q');
    expect(event).toBeDefined();
    expect(event?.outcome).toBe('diff');
  });

  it('release is a no-op and does not throw', () => {
    const coord = new LocalWorkQueueCoordinator();
    expect(() => coord.release(['a', 'b'], 'machine-x')).not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// Block 2: tick() with no sharedQueue — Local path, behavior-identical
// ---------------------------------------------------------------------------

describe('tick() with no sharedQueue (Local path)', () => {
  it('selects the expected items and writes ledger entries', async () => {
    const cfg = makeCfg({ daemon: { dailyBudgetUsd: 10, perTickItems: 2, parallel: 2, intervalMs: 100 } });
    mockLoadConfig.mockReturnValue(cfg);
    backlogItems = [
      makeItem('item-1', tmpRepo, { score: 3 }),
      makeItem('item-2', tmpRepo, { score: 2 }),
      makeItem('item-3', tmpRepo, { score: 1 }),
    ];
    mockBuildBacklog.mockImplementation(async () => ({
      generatedAt: new Date().toISOString(),
      repos: [tmpRepo],
      items: backlogItems,
    }));

    enroll(tmpRepo);
    const result = await tick(cfg, { dryRun: false });

    // perTickItems=2 → at most 2 items dispatched
    expect(result.itemsConsidered).toBeLessThanOrEqual(2);
    expect(result.reason).toBe('ok');

    // Ledger must have been written for dispatched items
    const ledger = loadWorkedLedger();
    expect(ledger.events.length).toBeGreaterThan(0);
    // All recorded items should be from our backlog
    const recordedIds = new Set(ledger.events.map(e => e.itemId));
    for (const id of recordedIds) {
      expect(['item-1', 'item-2', 'item-3']).toContain(id);
    }
  });

  it('cooldown-skipped items are not dispatched or recorded', async () => {
    const cfg = makeCfg({ daemon: { dailyBudgetUsd: 10, perTickItems: 3, parallel: 3, intervalMs: 100 } });
    mockLoadConfig.mockReturnValue(cfg);

    // Pre-record item-1 as 'empty' so it's in cooldown
    localRecord('item-1', 'empty');

    backlogItems = [
      makeItem('item-1', tmpRepo, { score: 5 }),
      makeItem('item-2', tmpRepo, { score: 3 }),
    ];
    mockBuildBacklog.mockImplementation(async () => ({
      generatedAt: new Date().toISOString(),
      repos: [tmpRepo],
      items: backlogItems,
    }));

    enroll(tmpRepo);
    await tick(cfg, { dryRun: false });

    // item-1 should not get a new ledger entry written by the tick
    // (the pre-existing 'empty' entry is there, but no new one from this tick)
    const ledger = loadWorkedLedger();
    const item1Events = ledger.events.filter(e => e.itemId === 'item-1');
    // Only the manually pre-recorded one; tick should not have dispatched it
    // (swarm was not called for item-1)
    const item1DispatchedTs = item1Events[item1Events.length - 1]?.ts;
    // item-2 should have been dispatched instead
    const item2Events = ledger.events.filter(e => e.itemId === 'item-2');
    expect(item2Events.length).toBeGreaterThan(0);
    // item-1's last event should be the pre-recorded one (not a new tick-recorded one)
    // We verify this by checking the mock call count excludes item-1's repo swarm-skip
    expect(item1Events.length).toBe(1); // only the pre-recorded entry
    void item1DispatchedTs; // used above
  });
});

// ---------------------------------------------------------------------------
// Block 3: SharedWorkQueueCoordinator — two-machine disjoint work
// ---------------------------------------------------------------------------

describe('SharedWorkQueueCoordinator two-machine disjoint', () => {
  it('tick() dry-run releases shared queue claims before returning', async () => {
    const sharedDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m113-shared-dry-'));
    try {
      const cfg = makeCfg({
        daemon: { dailyBudgetUsd: 10, perTickItems: 2, parallel: 2, intervalMs: 100 },
        fleet: {
          sharedQueue: {
            mode: 'filesystem',
            path: sharedDir,
            machineId: 'A',
            leaseMs: 30_000,
          },
        },
      });
      mockLoadConfig.mockReturnValue(cfg);
      backlogItems = [
        makeItem('dry-1', tmpRepo, { score: 3 }),
        makeItem('dry-2', tmpRepo, { score: 2 }),
      ];
      mockBuildBacklog.mockImplementation(async () => ({
        generatedAt: new Date().toISOString(),
        repos: [tmpRepo],
        items: backlogItems,
      }));

      enroll(tmpRepo);
      const result = await tick(cfg, { dryRun: true });

      expect(result.reason).toBe('dry-run');
      expect(new SharedStore(sharedDir, 30_000).readSnapshot().claims).toEqual({});
    } finally {
      fs.rmSync(sharedDir, { recursive: true, force: true });
    }
  });

  it('machines A and B claim disjoint items from the same backlog', () => {
    const sharedDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m113-shared-'));
    try {
      const leaseMs = 5 * 60 * 1000;
      const storeA = new SharedStore(sharedDir, leaseMs);
      const storeB = new SharedStore(sharedDir, leaseMs);
      const coordA = new SharedWorkQueueCoordinator(storeA, 'A', leaseMs);
      const coordB = new SharedWorkQueueCoordinator(storeB, 'B', leaseMs);

      const items: WorkItem[] = [
        makeItem('job-1', tmpRepo),
        makeItem('job-2', tmpRepo),
        makeItem('job-3', tmpRepo),
        makeItem('job-4', tmpRepo),
      ];

      // Machine A claims 2
      const claimedByA = coordA.claimItems(items, 2, 'A');
      // Machine B claims 2 from the same pool
      const claimedByB = coordB.claimItems(items, 2, 'B');

      const idsA = new Set(claimedByA.map(i => i.id));
      const idsB = new Set(claimedByB.map(i => i.id));

      // No overlap — disjoint sets
      for (const id of idsA) {
        expect(idsB.has(id)).toBe(false);
      }
      // Combined = at most 4 (all jobs), at least 2 each if supply allows
      const combined = new Set([...idsA, ...idsB]);
      expect(combined.size).toBe(idsA.size + idsB.size); // no duplicates
    } finally {
      fs.rmSync(sharedDir, { recursive: true, force: true });
    }
  });

  it('an item machine-A marked empty is globally skipped by machine-B within cooldown', () => {
    const sharedDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m113-shared2-'));
    try {
      const leaseMs = 5 * 60 * 1000;
      const storeA = new SharedStore(sharedDir, leaseMs);
      const storeB = new SharedStore(sharedDir, leaseMs);
      const coordA = new SharedWorkQueueCoordinator(storeA, 'A', leaseMs);
      const coordB = new SharedWorkQueueCoordinator(storeB, 'B', leaseMs);

      // Machine A records 'empty' for job-1
      coordA.recordOutcome('job-1', 'empty', 'A');

      // Machine B checks shouldSkip with a generous cooldown — should be true
      expect(coordB.shouldSkip('job-1', 60 * 60 * 1000)).toBe(true);

      // With a 0ms cooldown (nothing is < 0ms old → not skipped)
      expect(coordB.shouldSkip('job-1', 0)).toBe(false);

      // A 'diff' outcome does not trigger skip for the other machine
      coordA.recordOutcome('job-2', 'diff', 'A');
      expect(coordB.shouldSkip('job-2', 60 * 60 * 1000)).toBe(false);
    } finally {
      fs.rmSync(sharedDir, { recursive: true, force: true });
    }
  });

  it('released items become claimable again by another machine', () => {
    const sharedDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m113-shared3-'));
    try {
      const leaseMs = 5 * 60 * 1000;
      const storeA = new SharedStore(sharedDir, leaseMs);
      const storeB = new SharedStore(sharedDir, leaseMs);
      const coordA = new SharedWorkQueueCoordinator(storeA, 'A', leaseMs);
      const coordB = new SharedWorkQueueCoordinator(storeB, 'B', leaseMs);

      const items: WorkItem[] = [makeItem('job-x', tmpRepo)];

      // A claims job-x
      const claimed = coordA.claimItems(items, 1, 'A');
      expect(claimed.map(i => i.id)).toContain('job-x');

      // B cannot claim it while A holds the lease
      const claimedByB = coordB.claimItems(items, 1, 'B');
      expect(claimedByB.map(i => i.id)).not.toContain('job-x');

      // A releases it
      coordA.release(['job-x'], 'A');

      // Now B can claim it
      const claimedByBAfterRelease = coordB.claimItems(items, 1, 'B');
      expect(claimedByBAfterRelease.map(i => i.id)).toContain('job-x');
    } finally {
      fs.rmSync(sharedDir, { recursive: true, force: true });
    }
  });
});
