/**
 * m85.fleet-continuity.test.ts — per-repo fairness, worked-item cooldown,
 * live config reload.
 *
 * SAFETY GUARDRAILS (mirrors m48.fleet-supervisor.test.ts):
 *  - HOME is overridden to a tmp dir so no real ~/.ashlr state is touched.
 *  - runSwarm, runGoal, routeBackend, runAutoMergePass, buildBacklog are ALL
 *    MOCKED — no real agents, subprocesses, or API calls.
 *  - loadConfig is MOCKED so per-tick reload is controlled per test.
 *  - No real portfolio repos are touched.
 *  - ASHLR_IN_DAEMON / ASHLR_IN_SWARM are cleaned up in afterEach.
 *
 * Blocks:
 *  1. worked-ledger: recordOutcome + recentlyDeclined + never-throws.
 *  2. Fairness selection: 3 repos → items from each are selected.
 *  3. Cooldown skip: a recently-'empty' item is not dispatched.
 *  4. Config reload: a changed perTickItems value takes effect next tick.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import type { AshlrConfig, WorkItem } from '../src/core/types.js';
import type { RouteDecision } from '../src/core/fleet/router.js';

// ---------------------------------------------------------------------------
// HOME isolation — before any module import resolves homedir()
// ---------------------------------------------------------------------------

const origHome = process.env.HOME;
const origInDaemon = process.env.ASHLR_IN_DAEMON;
const origInSwarm = process.env.ASHLR_IN_SWARM;

let tmpHome: string;
let tmpRepo: string;
let tmpRepo2: string;
let tmpRepo3: string;

// ---------------------------------------------------------------------------
// Mocks — declared before lazy imports
// ---------------------------------------------------------------------------

const mockRunSwarm = vi.fn();
vi.mock('../src/core/swarm/runner.js', () => ({
  runSwarm: (...args: unknown[]) => mockRunSwarm(...args),
}));

const mockRunGoal = vi.fn();
vi.mock('../src/core/run/orchestrator.js', () => ({
  runGoal: (...args: unknown[]) => mockRunGoal(...args),
}));

let routeResult: RouteDecision = { backend: 'builtin', tier: 'local', reason: 'test' };
const mockRouteBackend = vi.fn();
vi.mock('../src/core/fleet/router.js', () => ({
  routeBackend: (...args: unknown[]) => mockRouteBackend(...args),
}));

const mockRunAutoMergePass = vi.fn();
vi.mock('../src/core/fleet/automerge-pass.js', () => ({
  runAutoMergePass: (...args: unknown[]) => mockRunAutoMergePass(...args),
}));

let backlogItems: WorkItem[] = [];
const mockBuildBacklog = vi.fn();
vi.mock('../src/core/portfolio/backlog.js', () => ({
  buildBacklog: (...args: unknown[]) => mockBuildBacklog(...args),
}));

// loadConfig mock — controllable per test via a mutable holder.
let liveCfgOverride: AshlrConfig | null = null;
const mockLoadConfig = vi.fn();
vi.mock('../src/core/config.js', () => ({
  loadConfig: (...args: unknown[]) => mockLoadConfig(...args),
  defaultConfig: () => ({ version: 1 }),
  saveConfig: vi.fn(),
}));

// ---------------------------------------------------------------------------
// Lazy imports — after mocks + HOME isolation
// ---------------------------------------------------------------------------

import { tick } from '../src/core/daemon/loop.js';
import { enroll, unenroll, setKill } from '../src/core/sandbox/policy.js';
import { createProposal } from '../src/core/inbox/store.js';
import {
  recordOutcome,
  recentlyDeclined,
  loadWorkedLedger,
  workedLedgerPath,
} from '../src/core/fleet/worked-ledger.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeCfg(overrides?: Partial<AshlrConfig>): AshlrConfig {
  return {
    version: 1,
    daemon: {
      dailyBudgetUsd: 10.0,
      perTickItems: 6,
      parallel: 6,
      intervalMs: 100,
    },
    ...overrides,
  } as AshlrConfig;
}

function initBareGitDir(dir: string): void {
  fs.mkdirSync(path.join(dir, '.git'), { recursive: true });
  fs.writeFileSync(path.join(dir, '.git', 'HEAD'), 'ref: refs/heads/main\n', 'utf8');
  fs.writeFileSync(
    path.join(dir, '.git', 'config'),
    '[core]\n\trepositoryformatversion = 0\n',
    'utf8',
  );
}

function makeItem(id: string, repo: string, over?: Partial<WorkItem>): WorkItem {
  return {
    id,
    repo,
    source: 'todo',
    title: `Item ${id}`,
    detail: `detail for ${id}`,
    value: 3,
    effort: 3,
    score: 1,
    tags: [],
    ts: new Date().toISOString(),
    ...over,
  };
}

function swarmStub(repo: string) {
  return async () => {
    createProposal({
      repo,
      origin: 'swarm',
      kind: 'patch',
      title: 'Mock swarm proposal',
      summary: 'Generated by mock runSwarm',
      diff: 'diff --git a/x.ts b/x.ts\n',
    });
    return {
      id: `mock-swarm-${Date.now()}`,
      status: 'done',
      goal: 'mock goal',
      result: 'mock result',
      usage: { estCostUsd: 0, totalTokens: 0, steps: 1 },
    };
  };
}

// ---------------------------------------------------------------------------
// beforeEach / afterEach
// ---------------------------------------------------------------------------

beforeEach(() => {
  tmpHome = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m85-home-'));
  tmpRepo  = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m85-repo-'));
  tmpRepo2 = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m85-repo2-'));
  tmpRepo3 = fs.mkdtempSync(path.join(os.tmpdir(), 'ashlr-m85-repo3-'));
  process.env.HOME = tmpHome;

  for (const r of [tmpRepo, tmpRepo2, tmpRepo3]) {
    initBareGitDir(r);
    fs.writeFileSync(path.join(r, 'package.json'), JSON.stringify({ name: 'r' }), 'utf8');
  }

  mockRunSwarm.mockReset();
  mockRunGoal.mockReset();
  mockRouteBackend.mockReset();
  mockRunAutoMergePass.mockReset();
  mockBuildBacklog.mockReset();
  mockLoadConfig.mockReset();

  routeResult = { backend: 'builtin', tier: 'local', reason: 'test' };
  backlogItems = [];
  liveCfgOverride = null;

  mockRouteBackend.mockImplementation(() => routeResult);
  mockRunAutoMergePass.mockImplementation(async () => ({ attempted: 0, merged: 0, results: [] }));
  mockBuildBacklog.mockImplementation(async () => ({
    generatedAt: new Date().toISOString(),
    repos: [tmpRepo, tmpRepo2, tmpRepo3],
    items: backlogItems,
  }));
  mockRunSwarm.mockImplementation(swarmStub(tmpRepo));
  mockRunGoal.mockImplementation(async () => ({
    id: `mock-run-${Date.now()}`,
    status: 'done',
    usage: { estCostUsd: 0 },
  }));
  // loadConfig returns the override if set, else the base cfg.
  mockLoadConfig.mockImplementation(() => liveCfgOverride ?? makeCfg());

  delete process.env.ASHLR_IN_DAEMON;
  delete process.env.ASHLR_IN_SWARM;
});

afterEach(() => {
  try { unenroll(tmpRepo); } catch { /* ignore */ }
  try { unenroll(tmpRepo2); } catch { /* ignore */ }
  try { unenroll(tmpRepo3); } catch { /* ignore */ }
  try { setKill(false); } catch { /* ignore */ }

  fs.rmSync(tmpHome,  { recursive: true, force: true });
  fs.rmSync(tmpRepo,  { recursive: true, force: true });
  fs.rmSync(tmpRepo2, { recursive: true, force: true });
  fs.rmSync(tmpRepo3, { recursive: true, force: true });

  process.env.HOME = origHome;
  if (origInDaemon !== undefined) process.env.ASHLR_IN_DAEMON = origInDaemon;
  else delete process.env.ASHLR_IN_DAEMON;
  if (origInSwarm !== undefined) process.env.ASHLR_IN_SWARM = origInSwarm;
  else delete process.env.ASHLR_IN_SWARM;

  vi.clearAllMocks();
});

// ===========================================================================
// 1. worked-ledger — pure unit tests (no tick(), no mocks needed)
// ===========================================================================

describe('M85 worked-ledger — pure unit', () => {
  it('recordOutcome persists an event and loadWorkedLedger returns it', () => {
    recordOutcome('item-abc', 'diff');
    const l = loadWorkedLedger();
    expect(l.events.some(e => e.itemId === 'item-abc' && e.outcome === 'diff')).toBe(true);
  });

  it('recentlyDeclined returns false when no entry exists', () => {
    expect(recentlyDeclined('unknown-item', 6 * 60 * 60 * 1000)).toBe(false);
  });

  it('recentlyDeclined returns false when last outcome is "diff"', () => {
    const ts = new Date(Date.now() - 1000).toISOString(); // 1 second ago
    recordOutcome('item-diff', 'diff', ts);
    expect(recentlyDeclined('item-diff', 6 * 60 * 60 * 1000)).toBe(false);
  });

  it('recentlyDeclined returns true within cooldown after "empty"', () => {
    const ts = new Date(Date.now() - 1000).toISOString(); // 1 second ago
    recordOutcome('item-empty', 'empty', ts);
    // Cooldown = 1 hour; 1 second ago is within 1h
    expect(recentlyDeclined('item-empty', 60 * 60 * 1000)).toBe(true);
  });

  it('recentlyDeclined returns false when "empty" is outside cooldown', () => {
    const old = new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(); // 2h ago
    recordOutcome('item-old-empty', 'empty', old);
    // Cooldown = 1h; 2h ago is outside
    expect(recentlyDeclined('item-old-empty', 60 * 60 * 1000)).toBe(false);
  });

  it('recentlyDeclined returns false when "diff" follows an "empty"', () => {
    const old = new Date(Date.now() - 1000).toISOString();
    const newer = new Date(Date.now() - 500).toISOString();
    recordOutcome('item-seq', 'empty', old);
    recordOutcome('item-seq', 'diff',  newer); // last event is 'diff'
    expect(recentlyDeclined('item-seq', 60 * 60 * 1000)).toBe(false);
  });

  it('never throws when the ledger file is missing', () => {
    // HOME already set to fresh tmpHome — file doesn't exist yet
    expect(() => recentlyDeclined('no-file-item', 1000)).not.toThrow();
    expect(() => loadWorkedLedger()).not.toThrow();
  });

  it('never throws when the ledger file is corrupt', () => {
    const p = workedLedgerPath();
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, '{ NOT VALID JSON !!!', 'utf8');
    expect(() => recentlyDeclined('bad-json', 1000)).not.toThrow();
    expect(() => loadWorkedLedger()).not.toThrow();
    // loadWorkedLedger should return a fresh empty ledger
    expect(loadWorkedLedger().events).toEqual([]);
  });

  it('recordOutcome never throws on a read-only directory (simulated by bad path)', () => {
    // Override HOME to a non-writable path won't work cross-platform easily,
    // so instead we verify the function signature: it returns void, no throw.
    expect(() => recordOutcome('x', 'empty')).not.toThrow();
  });
});

// ===========================================================================
// 2. Fairness selection — items from all 3 repos are selected
// ===========================================================================

describe('M85 fairness — round-robin across repos', () => {
  beforeEach(() => {
    enroll(tmpRepo);
    enroll(tmpRepo2);
    enroll(tmpRepo3);
  });

  it('selects at least one item from each of 3 repos when perTickItems >= 3', async () => {
    // Give each repo 2 items so the round-robin has something to pick.
    backlogItems = [
      makeItem('r1-a', tmpRepo,  { score: 5 }),
      makeItem('r1-b', tmpRepo,  { score: 4 }),
      makeItem('r2-a', tmpRepo2, { score: 5 }),
      makeItem('r2-b', tmpRepo2, { score: 4 }),
      makeItem('r3-a', tmpRepo3, { score: 5 }),
      makeItem('r3-b', tmpRepo3, { score: 4 }),
    ];

    const dispatched: string[] = [];
    mockRunSwarm.mockImplementation(async (_input: unknown, _cfg: unknown, opts: unknown) => {
      const o = opts as Record<string, unknown>;
      dispatched.push(o['project'] as string);
      return { id: 'sw', status: 'done', goal: '', result: '', usage: { estCostUsd: 0, totalTokens: 0, steps: 1 } };
    });

    // perTickItems = 6 so all 3 repos get at least one slot
    await tick(makeCfg({ daemon: { dailyBudgetUsd: 10, perTickItems: 6, parallel: 6, intervalMs: 100 } }), { dryRun: false });

    const reposSeen = new Set(dispatched);
    expect(reposSeen.has(tmpRepo)).toBe(true);
    expect(reposSeen.has(tmpRepo2)).toBe(true);
    expect(reposSeen.has(tmpRepo3)).toBe(true);
  });

  it('does NOT dispatch all items from a single repo when multiple repos have items', async () => {
    // Repo1 has 4 high-scoring items; repos 2 and 3 have 1 each.
    // Without fairness, the top-K slice would take all 4 from repo1 first.
    backlogItems = [
      makeItem('r1-a', tmpRepo,  { score: 10 }),
      makeItem('r1-b', tmpRepo,  { score: 9 }),
      makeItem('r1-c', tmpRepo,  { score: 8 }),
      makeItem('r1-d', tmpRepo,  { score: 7 }),
      makeItem('r2-a', tmpRepo2, { score: 3 }),
      makeItem('r3-a', tmpRepo3, { score: 2 }),
    ];

    const dispatched: string[] = [];
    mockRunSwarm.mockImplementation(async (_input: unknown, _cfg: unknown, opts: unknown) => {
      const o = opts as Record<string, unknown>;
      dispatched.push(o['project'] as string);
      return { id: 'sw', status: 'done', goal: '', result: '', usage: { estCostUsd: 0, totalTokens: 0, steps: 1 } };
    });

    // perTickItems = 3 — fairness should give each repo one slot
    await tick(makeCfg({ daemon: { dailyBudgetUsd: 10, perTickItems: 3, parallel: 3, intervalMs: 100 } }), { dryRun: false });

    const reposSeen = new Set(dispatched);
    // All three repos should have been visited
    expect(reposSeen.has(tmpRepo)).toBe(true);
    expect(reposSeen.has(tmpRepo2)).toBe(true);
    expect(reposSeen.has(tmpRepo3)).toBe(true);
    // Repo1 should NOT have consumed all 3 slots
    const repo1Count = dispatched.filter(r => r === tmpRepo).length;
    expect(repo1Count).toBeLessThan(3);
  });
});

// ===========================================================================
// 3. Cooldown skip — a recently-'empty' item is not re-dispatched
// ===========================================================================

describe('M85 cooldown skip — recentlyDeclined items are skipped', () => {
  beforeEach(() => {
    enroll(tmpRepo);
  });

  it('skips an item whose last outcome was "empty" within cooldown, dispatches the other', async () => {
    const cooledId = 'cooled-item';
    const freshId  = 'fresh-item';

    // Mark cooledId as recently empty (1 second ago, well within any cooldown).
    const recent = new Date(Date.now() - 1000).toISOString();
    recordOutcome(cooledId, 'empty', recent);

    backlogItems = [
      makeItem(cooledId, tmpRepo, { score: 10 }), // high score but cooled down
      makeItem(freshId,  tmpRepo, { score: 5  }), // lower score but fresh
    ];

    const dispatched: string[] = [];
    mockRunSwarm.mockImplementation(async (_input: unknown, _cfg: unknown, opts: unknown) => {
      const o = opts as Record<string, unknown>;
      // Capture which item title was used as the goal prefix
      const goalStr = (_input as Record<string, unknown>)?.['goal'] as string ?? '';
      dispatched.push(goalStr);
      createProposal({ repo: tmpRepo, origin: 'swarm', kind: 'patch', title: goalStr, summary: '', diff: 'diff\n' });
      return { id: 'sw', status: 'done', goal: goalStr, result: '', usage: { estCostUsd: 0, totalTokens: 0, steps: 1 } };
    });

    // cooldownMs set very large so the 1s-old empty record is within window.
    // We pass it via daemon.cooldownMs (read by the loop defensively).
    const cfg = {
      ...makeCfg(),
      daemon: { dailyBudgetUsd: 10, perTickItems: 3, parallel: 3, intervalMs: 100, cooldownMs: 6 * 60 * 60 * 1000 },
    } as unknown as AshlrConfig;
    liveCfgOverride = cfg;

    await tick(cfg, { dryRun: false });

    // Only the fresh item should have been dispatched
    expect(dispatched.some(g => g.includes(freshId))).toBe(true);
    expect(dispatched.some(g => g.includes(cooledId))).toBe(false);
  });

  it('dispatches a previously-empty item after the cooldown expires', async () => {
    const expiredId = 'expired-item';

    // Mark as empty 3 hours ago; cooldown is 1 hour → should NOT be skipped.
    const oldTs = new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString();
    recordOutcome(expiredId, 'empty', oldTs);

    backlogItems = [makeItem(expiredId, tmpRepo, { score: 5 })];

    const dispatched: string[] = [];
    mockRunSwarm.mockImplementation(async (_input: unknown, _cfg: unknown, opts: unknown) => {
      const o = opts as Record<string, unknown>;
      dispatched.push(o['project'] as string ?? '');
      return { id: 'sw', status: 'done', goal: '', result: '', usage: { estCostUsd: 0, totalTokens: 0, steps: 1 } };
    });

    // cooldownMs = 1h; the empty record is 3h old → not declined
    const cfg = {
      ...makeCfg(),
      daemon: { dailyBudgetUsd: 10, perTickItems: 3, parallel: 3, intervalMs: 100, cooldownMs: 60 * 60 * 1000 },
    } as unknown as AshlrConfig;
    liveCfgOverride = cfg;

    await tick(cfg, { dryRun: false });

    expect(dispatched.length).toBeGreaterThan(0);
  });
});

// ===========================================================================
// 4. Config reload — loadConfig is called per tick; changed values take effect
// ===========================================================================

describe('M85 config — tick honors its cfg arg (live reload is runDaemon\'s job)', () => {
  beforeEach(() => {
    enroll(tmpRepo);
    backlogItems = [makeItem('reload-1', tmpRepo), makeItem('reload-2', tmpRepo)];
  });

  it('honors perTickItems=1 from the passed cfg', async () => {
    const t = await tick(makeCfg({ daemon: { dailyBudgetUsd: 10, perTickItems: 1, parallel: 1, intervalMs: 100 } }), { dryRun: false });
    expect(t.itemsConsidered).toBe(1);
  });

  it('honors perTickItems=2 from the passed cfg', async () => {
    const t = await tick(makeCfg({ daemon: { dailyBudgetUsd: 10, perTickItems: 2, parallel: 2, intervalMs: 100 } }), { dryRun: false });
    expect(t.itemsConsidered).toBe(2);
  });

  it('uses the PASSED cfg, not the on-disk config (never clobbers an explicit cfg)', async () => {
    // loadConfig (mocked) returns perTickItems=5, but tick MUST honor its ARG (1).
    // The live reload happens in runDaemon's loop, not inside tick().
    liveCfgOverride = makeCfg({ daemon: { dailyBudgetUsd: 10, perTickItems: 5, parallel: 5, intervalMs: 100 } });
    const t = await tick(makeCfg({ daemon: { dailyBudgetUsd: 10, perTickItems: 1, parallel: 1, intervalMs: 100 } }), { dryRun: false });
    expect(t.itemsConsidered).toBe(1);
  });
});
