/**
 * Authenticated lifecycle receipts for the Agent OS observation producer.
 *
 * This ledger records only bounded digests, canonical timestamps, and an opaque
 * attempt UUID. It grants no authority and deliberately shares the existing
 * host provenance HMAC: the receipts are tamper-evident to cooperative local
 * processes, but are not an independent verifier or rollback protection.
 */

import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, isAbsolute, join, parse, resolve } from 'node:path';

import {
  loadExistingProvenanceKey,
  loadExistingProvenanceKeyReadOnly,
} from '../foundry/provenance.js';
import {
  acquireLocalStoreLock,
  releaseLocalStoreLock,
} from '../fleet/local-store-lock.js';
import {
  readImmutablePrivateRecords,
  writeImmutablePrivateRecord,
  type ImmutablePrivateRecordCodec,
  type ImmutablePrivateRecordReadOptions,
  type ImmutablePrivateRecordReadStopReason,
  type ImmutablePrivateRecordStoreConfig,
} from '../util/immutable-private-record-store.js';

const PROTOCOL = 'agent-os-observer-attempt-v1' as const;
const RECORD_TYPE = 'agent-os-observer-attempt' as const;
const GENESIS_DIGEST = '0'.repeat(64);
const SHA256_RE = /^(?:sha256:)?[a-f0-9]{64}$/;
const PLAIN_SHA256_RE = /^[a-f0-9]{64}$/;
const UUID_V4_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const RECORD_FILE_RE = /^([0-9a-f-]{36})\.([12])\.([a-f0-9]{64})\.json$/;
const MAX_RECORD_BYTES = 8 * 1_024;
const MAX_RECORDS = 8_192;
const MAX_AGGREGATE_BYTES = 64 * 1_024 * 1_024;
const MAX_LOCK_WAIT_MS = 2_000;
const MAX_SNAPSHOT_SEQUENCE = 4_096;

export const AGENT_OS_OBSERVER_ATTEMPT_GENESIS_DIGEST = GENESIS_DIGEST;
export const AGENT_OS_OBSERVER_ATTEMPT_MAX_RECORDS = MAX_RECORDS;

export type AgentOsObserverTerminalOutcomeV1 =
  | 'completed'
  | 'replayed'
  | 'source-incomplete'
  | 'source-invalid'
  | 'cancelled-before-commit'
  | 'deadline-before-commit'
  | 'append-failed'
  | 'ambiguous-after-commit';

export interface AgentOsObserverAttemptStartInputV1 {
  attemptId: string;
  initiatingTickDigest: string;
  initiatingTickAt: string;
  /** Exact claimed source identity. Production scheduling requires a verified digest. */
  bundleDigest: string | null;
  startedAt: string;
  deadlineAt: string;
}

export interface AgentOsObserverAttemptTerminalInputV1 extends
  AgentOsObserverAttemptStartInputV1 {
  outcome: AgentOsObserverTerminalOutcomeV1;
  snapshotDigest: string | null;
  snapshotEnvelopeDigest: string | null;
  snapshotEnvelopeSequence: number | null;
  completedAt: string;
}

export interface AgentOsObserverAttemptReceiptV1 {
  schemaVersion: 1;
  protocol: typeof PROTOCOL;
  recordType: typeof RECORD_TYPE;
  authority: 'observation-only';
  effectAuthority: 'none';
  planningAuthority: false;
  executionAuthority: false;
  proposalAuthority: false;
  mergeAuthority: false;
  releaseAuthority: false;
  deployAuthority: false;
  publicationAuthority: false;
  externalMutationAuthority: false;
  learningAuthority: false;
  policyEligible: false;
  sameUserTamperResistant: false;
  rollbackProtected: false;
  historicalAuthority: false;
  attestationAuthority: 'host-shared-hmac';
  verifierIsolated: false;
  attemptId: string;
  transitionOrdinal: 1 | 2;
  phase: 'started' | 'terminal';
  terminalOutcome: AgentOsObserverTerminalOutcomeV1 | null;
  initiatingTickDigest: string;
  initiatingTickAt: string;
  bundleDigest: string | null;
  snapshotDigest: string | null;
  snapshotEnvelopeDigest: string | null;
  snapshotEnvelopeSequence: number | null;
  startedAt: string;
  deadlineAt: string;
  completedAt: string | null;
  previousReceiptDigest: string;
  receiptDigest: string;
  attestation: string;
}

export interface AgentOsObserverAttemptStoreDependenciesV1 {
  /** Existing trusted directory that directly contains rootPath. */
  anchorPath: string;
  rootPath: string;
  /** Existing 32-byte provenance HMAC. Never generated by this module. */
  key: Buffer | null;
  /** Hermetic capacity seam; production leaves this unset. */
  maxRecords?: number;
}

export type AgentOsObserverAttemptWriteDispositionV1 =
  | 'recorded'
  | 'replayed'
  | 'conflicted'
  | 'invalid'
  | 'invalid-transition'
  | 'capacity-exhausted'
  | 'key-unavailable'
  | 'store-unavailable'
  | 'persistence-failed';

export type AgentOsObserverAttemptWriteResultV1 =
  | {
      disposition: 'recorded' | 'replayed';
      receipt: AgentOsObserverAttemptReceiptV1;
    }
  | {
      disposition: Exclude<AgentOsObserverAttemptWriteDispositionV1, 'recorded' | 'replayed'>;
      receipt: null;
    };

export type AgentOsObserverAttemptReadStopReasonV1 =
  | ImmutablePrivateRecordReadStopReason
  | 'key-unavailable'
  | 'transition-gap'
  | 'transition-fork'
  | 'invalid-transition'
  | 'non-monotonic-transition';

export interface AgentOsObserverAttemptReadResultV1 {
  records: AgentOsObserverAttemptReceiptV1[];
  sourceState: 'missing' | 'healthy' | 'degraded';
  sourcePresent: boolean;
  complete: boolean;
  stopReasons: AgentOsObserverAttemptReadStopReasonV1[];
  filesRead: number;
  bytesRead: number;
  invalidFiles: number;
  limitExceeded: boolean;
  /** Durable-derived capacity state; true means no complete new attempt can fit. */
  capacityExhausted: boolean;
  authority: 'observation-only';
  effectAuthority: 'none';
}

const AUTHORITY = Object.freeze({
  authority: 'observation-only' as const,
  effectAuthority: 'none' as const,
  planningAuthority: false as const,
  executionAuthority: false as const,
  proposalAuthority: false as const,
  mergeAuthority: false as const,
  releaseAuthority: false as const,
  deployAuthority: false as const,
  publicationAuthority: false as const,
  externalMutationAuthority: false as const,
  learningAuthority: false as const,
  policyEligible: false as const,
  sameUserTamperResistant: false as const,
  rollbackProtected: false as const,
  historicalAuthority: false as const,
  attestationAuthority: 'host-shared-hmac' as const,
  verifierIsolated: false as const,
});

const RECEIPT_KEYS = new Set([
  'schemaVersion', 'protocol', 'recordType', 'authority', 'effectAuthority',
  'planningAuthority', 'executionAuthority', 'proposalAuthority', 'mergeAuthority',
  'releaseAuthority', 'deployAuthority', 'publicationAuthority', 'externalMutationAuthority',
  'learningAuthority', 'policyEligible', 'sameUserTamperResistant', 'rollbackProtected',
  'historicalAuthority', 'attestationAuthority', 'verifierIsolated', 'attemptId',
  'transitionOrdinal', 'phase', 'terminalOutcome', 'initiatingTickDigest',
  'initiatingTickAt', 'bundleDigest', 'snapshotDigest', 'snapshotEnvelopeDigest',
  'snapshotEnvelopeSequence', 'startedAt', 'deadlineAt', 'completedAt',
  'previousReceiptDigest', 'receiptDigest', 'attestation',
]);
const START_INPUT_KEYS = new Set([
  'attemptId', 'initiatingTickDigest', 'initiatingTickAt', 'bundleDigest', 'startedAt', 'deadlineAt',
]);
const TERMINAL_INPUT_KEYS = new Set([
  ...START_INPUT_KEYS, 'outcome', 'bundleDigest', 'snapshotDigest',
  'snapshotEnvelopeDigest', 'snapshotEnvelopeSequence', 'completedAt',
]);
const TERMINAL_OUTCOMES = new Set<AgentOsObserverTerminalOutcomeV1>([
  'completed', 'replayed', 'source-incomplete', 'source-invalid',
  'cancelled-before-commit', 'deadline-before-commit', 'append-failed',
  'ambiguous-after-commit',
]);

type UnsignedReceipt = Omit<AgentOsObserverAttemptReceiptV1, 'receiptDigest' | 'attestation'>;

function recordOf(value: unknown): Record<string, unknown> | null {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return null;
  try {
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) return null;
    const keys = Reflect.ownKeys(value);
    if (keys.some((key) => typeof key !== 'string')) return null;
    const descriptors = Object.getOwnPropertyDescriptors(value);
    if (keys.some((key) => {
      const descriptor = descriptors[String(key)];
      return !descriptor?.enumerable || !('value' in descriptor);
    })) return null;
    return value as Record<string, unknown>;
  } catch {
    return null;
  }
}

function exactKeys(value: Record<string, unknown>, expected: ReadonlySet<string>): boolean {
  const keys = Object.keys(value);
  return keys.length === expected.size && keys.every((key) => expected.has(key));
}

function canonicalTimestamp(value: unknown): value is string {
  if (typeof value !== 'string' || value.length > 40) return false;
  const milliseconds = Date.parse(value);
  return Number.isFinite(milliseconds) && new Date(milliseconds).toISOString() === value;
}

function digest(value: unknown): value is string {
  return typeof value === 'string' && SHA256_RE.test(value);
}

function plainDigest(value: unknown): value is string {
  return typeof value === 'string' && PLAIN_SHA256_RE.test(value);
}

function sameDigest(left: unknown, right: unknown): boolean {
  if (!digest(left) || !digest(right)) return false;
  const normalizedLeft = left.replace(/^sha256:/u, '');
  const normalizedRight = right.replace(/^sha256:/u, '');
  const first = Buffer.from(normalizedLeft, 'hex');
  const second = Buffer.from(normalizedRight, 'hex');
  return first.length === second.length && timingSafeEqual(first, second);
}

function sha(domain: string, value: unknown): string {
  return createHash('sha256').update(JSON.stringify([domain, value]), 'utf8').digest('hex');
}

function hmac(key: Buffer, domain: string, value: unknown): string {
  return createHmac('sha256', key).update(JSON.stringify([domain, value]), 'utf8').digest('hex');
}

function validDependencies(value: AgentOsObserverAttemptStoreDependenciesV1): boolean {
  try {
    const anchor = resolve(value.anchorPath);
    const root = resolve(value.rootPath);
    return value.anchorPath === anchor && value.rootPath === root && isAbsolute(anchor) && isAbsolute(root) &&
      anchor !== parse(anchor).root && root !== anchor && dirname(root) === anchor &&
      (value.key === null || (Buffer.isBuffer(value.key) && value.key.length === 32)) &&
      (value.maxRecords === undefined ||
        (Number.isSafeInteger(value.maxRecords) && value.maxRecords >= 2 && value.maxRecords <= MAX_RECORDS));
  } catch {
    return false;
  }
}

function validStartInput(value: unknown): value is AgentOsObserverAttemptStartInputV1 {
  const row = recordOf(value);
  if (!row || !exactKeys(row, START_INPUT_KEYS)) return false;
  const input = value as AgentOsObserverAttemptStartInputV1;
  if (!UUID_V4_RE.test(input.attemptId) || !plainDigest(input.initiatingTickDigest) ||
    !canonicalTimestamp(input.initiatingTickAt) || !canonicalTimestamp(input.startedAt) ||
    !canonicalTimestamp(input.deadlineAt) ||
    (input.bundleDigest !== null && !digest(input.bundleDigest))) return false;
  const tickAt = Date.parse(input.initiatingTickAt);
  const startedAt = Date.parse(input.startedAt);
  const deadlineAt = Date.parse(input.deadlineAt);
  return tickAt <= startedAt && startedAt < deadlineAt;
}

function validTerminalBindings(input: AgentOsObserverAttemptTerminalInputV1): boolean {
  const bundle = input.bundleDigest;
  const snapshot = input.snapshotDigest;
  const envelope = input.snapshotEnvelopeDigest;
  const sequence = input.snapshotEnvelopeSequence;
  const noSnapshotEnvelope = envelope === null && sequence === null;
  const exactSnapshotEnvelope = plainDigest(envelope) && Number.isSafeInteger(sequence) &&
    Number(sequence) >= 1 && Number(sequence) <= MAX_SNAPSHOT_SEQUENCE;

  if (input.outcome === 'completed' || input.outcome === 'replayed') {
    return digest(bundle) && digest(snapshot) && exactSnapshotEnvelope;
  }
  if (input.outcome === 'append-failed' || input.outcome === 'ambiguous-after-commit') {
    return digest(bundle) && digest(snapshot) && noSnapshotEnvelope;
  }
  if (input.outcome === 'source-incomplete' || input.outcome === 'source-invalid') {
    // A malformed or unavailable source may not carry even a syntactically
    // valid claimed digest. The durable attempt must still close; null here is
    // an explicit absence, never an authenticated source identity.
    return (bundle === null || digest(bundle)) && snapshot === null && noSnapshotEnvelope;
  }
  return (bundle === null || digest(bundle)) && snapshot === null && noSnapshotEnvelope;
}

function validTerminalInput(value: unknown): value is AgentOsObserverAttemptTerminalInputV1 {
  const row = recordOf(value);
  if (!row || !exactKeys(row, TERMINAL_INPUT_KEYS)) return false;
  const input = value as AgentOsObserverAttemptTerminalInputV1;
  if (!TERMINAL_OUTCOMES.has(input.outcome) || !validStartInput({
    attemptId: input.attemptId,
    initiatingTickDigest: input.initiatingTickDigest,
    initiatingTickAt: input.initiatingTickAt,
    bundleDigest: input.bundleDigest,
    startedAt: input.startedAt,
    deadlineAt: input.deadlineAt,
  }) || !canonicalTimestamp(input.completedAt) || Date.parse(input.completedAt) < Date.parse(input.startedAt) ||
    (input.outcome === 'deadline-before-commit' && Date.parse(input.completedAt) < Date.parse(input.deadlineAt)) ||
    ((input.outcome === 'completed' || input.outcome === 'replayed') &&
      Date.parse(input.completedAt) >= Date.parse(input.deadlineAt))) {
    return false;
  }
  return validTerminalBindings(input);
}

function unsignedStart(input: AgentOsObserverAttemptStartInputV1): UnsignedReceipt {
  return {
    schemaVersion: 1,
    protocol: PROTOCOL,
    recordType: RECORD_TYPE,
    ...AUTHORITY,
    attemptId: input.attemptId,
    transitionOrdinal: 1,
    phase: 'started',
    terminalOutcome: null,
    initiatingTickDigest: input.initiatingTickDigest,
    initiatingTickAt: input.initiatingTickAt,
    bundleDigest: input.bundleDigest,
    snapshotDigest: null,
    snapshotEnvelopeDigest: null,
    snapshotEnvelopeSequence: null,
    startedAt: input.startedAt,
    deadlineAt: input.deadlineAt,
    completedAt: null,
    previousReceiptDigest: GENESIS_DIGEST,
  };
}

function unsignedTerminal(
  input: AgentOsObserverAttemptTerminalInputV1,
  start: AgentOsObserverAttemptReceiptV1,
): UnsignedReceipt {
  return {
    schemaVersion: 1,
    protocol: PROTOCOL,
    recordType: RECORD_TYPE,
    ...AUTHORITY,
    attemptId: input.attemptId,
    transitionOrdinal: 2,
    phase: 'terminal',
    terminalOutcome: input.outcome,
    initiatingTickDigest: input.initiatingTickDigest,
    initiatingTickAt: input.initiatingTickAt,
    bundleDigest: input.bundleDigest,
    snapshotDigest: input.snapshotDigest,
    snapshotEnvelopeDigest: input.snapshotEnvelopeDigest,
    snapshotEnvelopeSequence: input.snapshotEnvelopeSequence,
    startedAt: input.startedAt,
    deadlineAt: input.deadlineAt,
    completedAt: input.completedAt,
    previousReceiptDigest: start.receiptDigest,
  };
}

function seal(unsigned: UnsignedReceipt, key: Buffer): AgentOsObserverAttemptReceiptV1 {
  const receiptDigest = sha('ashlr:agent-os-observer-attempt:receipt:v1', unsigned);
  const attestation = hmac(key, 'ashlr:agent-os-observer-attempt:attestation:v1', [
    receiptDigest,
    unsigned.attemptId,
    unsigned.transitionOrdinal,
  ]);
  return { ...unsigned, receiptDigest, attestation };
}

function reconstructWithKey(value: unknown, key: Buffer): AgentOsObserverAttemptReceiptV1 | null {
  const row = recordOf(value);
  if (key.length !== 32 || !row || !exactKeys(row, RECEIPT_KEYS) || row['schemaVersion'] !== 1 ||
    row['protocol'] !== PROTOCOL || row['recordType'] !== RECORD_TYPE ||
    row['authority'] !== 'observation-only' || row['effectAuthority'] !== 'none' ||
    row['planningAuthority'] !== false || row['executionAuthority'] !== false ||
    row['proposalAuthority'] !== false || row['mergeAuthority'] !== false ||
    row['releaseAuthority'] !== false || row['deployAuthority'] !== false ||
    row['publicationAuthority'] !== false || row['externalMutationAuthority'] !== false ||
    row['learningAuthority'] !== false || row['policyEligible'] !== false ||
    row['sameUserTamperResistant'] !== false || row['rollbackProtected'] !== false ||
    row['historicalAuthority'] !== false || row['attestationAuthority'] !== 'host-shared-hmac' ||
    row['verifierIsolated'] !== false || typeof row['attemptId'] !== 'string' ||
    !UUID_V4_RE.test(row['attemptId']) || !plainDigest(row['initiatingTickDigest']) ||
    !canonicalTimestamp(row['initiatingTickAt']) || !canonicalTimestamp(row['startedAt']) ||
    !canonicalTimestamp(row['deadlineAt']) || !plainDigest(row['previousReceiptDigest']) ||
    !plainDigest(row['receiptDigest']) || !plainDigest(row['attestation'])) return null;

  const phase = row['phase'];
  const ordinal = row['transitionOrdinal'];
  const startedShape = ordinal === 1 && phase === 'started' && row['terminalOutcome'] === null &&
    (row['bundleDigest'] === null || digest(row['bundleDigest'])) &&
    row['snapshotDigest'] === null && row['snapshotEnvelopeDigest'] === null &&
    row['snapshotEnvelopeSequence'] === null && row['completedAt'] === null &&
    row['previousReceiptDigest'] === GENESIS_DIGEST;
  const terminalShape = ordinal === 2 && phase === 'terminal' &&
    typeof row['terminalOutcome'] === 'string' && TERMINAL_OUTCOMES.has(row['terminalOutcome'] as AgentOsObserverTerminalOutcomeV1) &&
    canonicalTimestamp(row['completedAt']);
  if (!startedShape && !terminalShape) return null;

  const unsigned = { ...row } as Record<string, unknown>;
  delete unsigned['receiptDigest'];
  delete unsigned['attestation'];
  const receiptDigest = sha('ashlr:agent-os-observer-attempt:receipt:v1', unsigned);
  const attestation = hmac(key, 'ashlr:agent-os-observer-attempt:attestation:v1', [
    receiptDigest,
    row['attemptId'],
    ordinal,
  ]);
  if (!sameDigest(row['receiptDigest'], receiptDigest) || !sameDigest(row['attestation'], attestation)) return null;

  const receipt = row as unknown as AgentOsObserverAttemptReceiptV1;
  const startLike = {
    attemptId: receipt.attemptId,
    initiatingTickDigest: receipt.initiatingTickDigest,
    initiatingTickAt: receipt.initiatingTickAt,
    bundleDigest: receipt.bundleDigest,
    startedAt: receipt.startedAt,
    deadlineAt: receipt.deadlineAt,
  };
  if (!validStartInput(startLike)) return null;
  if (receipt.phase === 'terminal') {
    if (!validTerminalInput({
      ...startLike,
      outcome: receipt.terminalOutcome!,
      bundleDigest: receipt.bundleDigest,
      snapshotDigest: receipt.snapshotDigest,
      snapshotEnvelopeDigest: receipt.snapshotEnvelopeDigest,
      snapshotEnvelopeSequence: receipt.snapshotEnvelopeSequence,
      completedAt: receipt.completedAt!,
    })) return null;
  }
  return { ...receipt };
}

function receiptCodec(key: Buffer): ImmutablePrivateRecordCodec<AgentOsObserverAttemptReceiptV1> {
  return {
    parse: (value) => reconstructWithKey(value, key),
    serialize: (receipt) => `${JSON.stringify(receipt)}\n`,
    recordId: (receipt) => receipt.receiptDigest,
    recordFileName: (receipt) =>
      `${receipt.attemptId}.${receipt.transitionOrdinal}.${receipt.receiptDigest}.json`,
    isRecordFileName: (fileName) => RECORD_FILE_RE.test(fileName),
    stageToken: (receipt) => hmac(
      key,
      'ashlr:agent-os-observer-attempt:publication-stage:v1',
      receipt.receiptDigest,
    ).slice(0, 32),
    equivalent: (left, right) => sameDigest(left.receiptDigest, right.receiptDigest) &&
      sameDigest(left.attestation, right.attestation),
    compare: (left, right) => left.attemptId.localeCompare(right.attemptId) ||
      left.transitionOrdinal - right.transitionOrdinal ||
      left.receiptDigest.localeCompare(right.receiptDigest),
  };
}

export function agentOsObserverAttemptStoreRootPath(): string {
  return resolve(join(homedir(), '.ashlr', 'agent-os-observer-attempts-v1'));
}

export function defaultAgentOsObserverAttemptStoreDependenciesV1(
  access: 'read' | 'write',
): AgentOsObserverAttemptStoreDependenciesV1 | null {
  try {
    const home = resolve(homedir());
    if (!isAbsolute(home) || home === parse(home).root) return null;
    const anchorPath = join(home, '.ashlr');
    const key = access === 'read'
      ? loadExistingProvenanceKeyReadOnly()
      : loadExistingProvenanceKey();
    return {
      anchorPath,
      rootPath: join(anchorPath, 'agent-os-observer-attempts-v1'),
      key: key?.length === 32 ? key : null,
    };
  } catch {
    return null;
  }
}

function storeConfig(
  dependencies: AgentOsObserverAttemptStoreDependenciesV1,
): ImmutablePrivateRecordStoreConfig<AgentOsObserverAttemptReceiptV1> {
  const maxRecords = dependencies.maxRecords ?? MAX_RECORDS;
  return {
    label: 'Agent OS observer attempt',
    anchorPath: dependencies.anchorPath,
    rootPath: dependencies.rootPath,
    lockFileName: '.attempt-ledger.lock',
    maxRecordBytes: MAX_RECORD_BYTES,
    defaultMaxFiles: maxRecords,
    hardMaxFiles: maxRecords,
    defaultMaxBytes: MAX_AGGREGATE_BYTES,
    hardMaxBytes: MAX_AGGREGATE_BYTES,
    codecForWrite: () => dependencies.key?.length === 32 ? receiptCodec(dependencies.key) : null,
    codecForRead: () => dependencies.key?.length === 32 ? receiptCodec(dependencies.key) : null,
  };
}

function emptyRead(
  sourceState: AgentOsObserverAttemptReadResultV1['sourceState'],
  stopReasons: AgentOsObserverAttemptReadStopReasonV1[],
): AgentOsObserverAttemptReadResultV1 {
  return {
    records: [],
    sourceState,
    sourcePresent: false,
    complete: sourceState !== 'degraded',
    stopReasons,
    filesRead: 0,
    bytesRead: 0,
    invalidFiles: 0,
    limitExceeded: false,
    capacityExhausted: false,
    authority: 'observation-only',
    effectAuthority: 'none',
  };
}

function sameStartBinding(
  receipt: AgentOsObserverAttemptReceiptV1,
  input: AgentOsObserverAttemptStartInputV1,
): boolean {
  return receipt.attemptId === input.attemptId &&
    sameDigest(receipt.initiatingTickDigest, input.initiatingTickDigest) &&
    receipt.initiatingTickAt === input.initiatingTickAt &&
    ((receipt.bundleDigest === null && input.bundleDigest === null) ||
      sameDigest(receipt.bundleDigest, input.bundleDigest)) &&
    receipt.startedAt === input.startedAt && receipt.deadlineAt === input.deadlineAt;
}

function validateTransitions(
  records: readonly AgentOsObserverAttemptReceiptV1[],
): AgentOsObserverAttemptReadStopReasonV1[] {
  const reasons = new Set<AgentOsObserverAttemptReadStopReasonV1>();
  const byAttempt = new Map<string, AgentOsObserverAttemptReceiptV1[]>();
  for (const receipt of records) {
    const current = byAttempt.get(receipt.attemptId) ?? [];
    current.push(receipt);
    byAttempt.set(receipt.attemptId, current);
  }
  for (const attempt of byAttempt.values()) {
    const starts = attempt.filter((receipt) => receipt.transitionOrdinal === 1);
    const terminals = attempt.filter((receipt) => receipt.transitionOrdinal === 2);
    if (starts.length > 1 || terminals.length > 1) reasons.add('transition-fork');
    if (starts.length === 0 && terminals.length > 0) reasons.add('transition-gap');
    if (starts.length !== 1 || terminals.length === 0) continue;
    const start = starts[0]!;
    for (const terminal of terminals) {
      if (!sameStartBinding(terminal, start) || !sameDigest(terminal.previousReceiptDigest, start.receiptDigest)) {
        reasons.add('invalid-transition');
      }
      if (terminal.completedAt === null || Date.parse(terminal.completedAt) < Date.parse(start.startedAt)) {
        reasons.add('non-monotonic-transition');
      }
    }
  }
  return [...reasons];
}

export function readAgentOsObserverAttemptReceiptsV1(
  dependencies: AgentOsObserverAttemptStoreDependenciesV1 | null =
    defaultAgentOsObserverAttemptStoreDependenciesV1('read'),
  options: ImmutablePrivateRecordReadOptions = {},
): AgentOsObserverAttemptReadResultV1 {
  if (!dependencies || !validDependencies(dependencies)) return emptyRead('degraded', ['invalid-options']);
  if (!dependencies.key) return emptyRead('degraded', ['key-unavailable']);
  const raw = readImmutablePrivateRecords(storeConfig(dependencies), { ...options, requireComplete: false });
  if (raw.sourceState === 'missing') {
    return {
      ...raw,
      records: [],
      capacityExhausted: false,
      authority: 'observation-only',
      effectAuthority: 'none',
    };
  }
  const transitionReasons = validateTransitions(raw.records);
  const stopReasons = [...new Set<AgentOsObserverAttemptReadStopReasonV1>([
    ...raw.stopReasons,
    ...transitionReasons,
  ])];
  const degraded = raw.sourceState === 'degraded' || stopReasons.length > 0;
  return {
    ...raw,
    records: degraded && options.requireComplete === true ? [] : raw.records,
    sourceState: degraded ? 'degraded' : 'healthy',
    complete: !degraded,
    stopReasons,
    capacityExhausted: raw.records.length + 2 > recordCapacity(dependencies),
    authority: 'observation-only',
    effectAuthority: 'none',
  };
}

function transitionLockPath(dependencies: AgentOsObserverAttemptStoreDependenciesV1): string {
  return join(dependencies.anchorPath, '.agent-os-observer-attempt-transition.lock');
}

function recordCapacity(dependencies: AgentOsObserverAttemptStoreDependenciesV1): number {
  return dependencies.maxRecords ?? MAX_RECORDS;
}

function writeReceipt(
  receipt: AgentOsObserverAttemptReceiptV1,
  dependencies: AgentOsObserverAttemptStoreDependenciesV1,
  lockWaitMs: number,
): AgentOsObserverAttemptWriteResultV1 {
  const disposition = writeImmutablePrivateRecord(storeConfig(dependencies), receipt, { lockWaitMs });
  if (disposition === 'recorded' || disposition === 'replayed') return { disposition, receipt };
  return {
    disposition: disposition === 'conflicted' ? 'conflicted' :
      disposition === 'invalid' ? 'invalid' : 'persistence-failed',
    receipt: null,
  };
}

function boundedLockWait(value: number | undefined): number | null {
  if (value === undefined) return MAX_LOCK_WAIT_MS;
  return Number.isFinite(value) ? Math.max(0, Math.min(MAX_LOCK_WAIT_MS, Math.floor(value))) : null;
}

export function beginAgentOsObserverAttemptV1(
  input: AgentOsObserverAttemptStartInputV1,
  dependencies: AgentOsObserverAttemptStoreDependenciesV1 | null =
    defaultAgentOsObserverAttemptStoreDependenciesV1('write'),
  options: { lockWaitMs?: number } = {},
): AgentOsObserverAttemptWriteResultV1 {
  if (!validStartInput(input)) return { disposition: 'invalid', receipt: null };
  if (!dependencies || !validDependencies(dependencies)) return { disposition: 'store-unavailable', receipt: null };
  if (!dependencies.key) return { disposition: 'key-unavailable', receipt: null };
  const lockWaitMs = boundedLockWait(options.lockWaitMs);
  if (lockWaitMs === null) return { disposition: 'invalid', receipt: null };
  if (!existsSync(dependencies.anchorPath)) return { disposition: 'store-unavailable', receipt: null };
  const transitionLock = acquireLocalStoreLock(
    transitionLockPath(dependencies),
    lockWaitMs,
    { anchorPath: dependencies.anchorPath, exactPrivateStorage: true },
  );
  if (!transitionLock) return { disposition: 'store-unavailable', receipt: null };
  try {
    const read = readAgentOsObserverAttemptReceiptsV1(dependencies, { requireComplete: true });
    if (read.sourceState === 'degraded') return { disposition: 'store-unavailable', receipt: null };
    const attempt = read.records.filter((receipt) => receipt.attemptId === input.attemptId);
    const existingStart = attempt.find((receipt) => receipt.transitionOrdinal === 1);
    if (existingStart && !sameStartBinding(existingStart, input)) {
      return { disposition: 'conflicted', receipt: null };
    }
    if (read.records.length >= recordCapacity(dependencies) && !existingStart) {
      return { disposition: 'capacity-exhausted', receipt: null };
    }
    return writeReceipt(seal(unsignedStart(input), dependencies.key), dependencies, lockWaitMs);
  } finally {
    releaseLocalStoreLock(transitionLock);
  }
}

export function completeAgentOsObserverAttemptV1(
  input: AgentOsObserverAttemptTerminalInputV1,
  dependencies: AgentOsObserverAttemptStoreDependenciesV1 | null =
    defaultAgentOsObserverAttemptStoreDependenciesV1('write'),
  options: { lockWaitMs?: number } = {},
): AgentOsObserverAttemptWriteResultV1 {
  if (!validTerminalInput(input)) return { disposition: 'invalid', receipt: null };
  if (!dependencies || !validDependencies(dependencies)) return { disposition: 'store-unavailable', receipt: null };
  if (!dependencies.key) return { disposition: 'key-unavailable', receipt: null };
  const lockWaitMs = boundedLockWait(options.lockWaitMs);
  if (lockWaitMs === null) return { disposition: 'invalid', receipt: null };
  if (!existsSync(dependencies.anchorPath)) return { disposition: 'store-unavailable', receipt: null };
  const transitionLock = acquireLocalStoreLock(
    transitionLockPath(dependencies),
    lockWaitMs,
    { anchorPath: dependencies.anchorPath, exactPrivateStorage: true },
  );
  if (!transitionLock) return { disposition: 'store-unavailable', receipt: null };
  try {
    const read = readAgentOsObserverAttemptReceiptsV1(dependencies, { requireComplete: true });
    if (read.sourceState === 'degraded') return { disposition: 'store-unavailable', receipt: null };
    const attempt = read.records.filter((receipt) => receipt.attemptId === input.attemptId);
    const starts = attempt.filter((receipt) => receipt.transitionOrdinal === 1);
    const terminals = attempt.filter((receipt) => receipt.transitionOrdinal === 2);
    if (starts.length !== 1 || !sameStartBinding(starts[0]!, input)) {
      return { disposition: 'invalid-transition', receipt: null };
    }
    const candidate = seal(unsignedTerminal(input, starts[0]!), dependencies.key);
    if (terminals.length > 0) {
      return terminals.length === 1 && sameDigest(terminals[0]!.receiptDigest, candidate.receiptDigest)
        ? writeReceipt(candidate, dependencies, lockWaitMs)
        : { disposition: 'conflicted', receipt: null };
    }
    if (read.records.length >= recordCapacity(dependencies)) {
      return { disposition: 'capacity-exhausted', receipt: null };
    }
    return writeReceipt(candidate, dependencies, lockWaitMs);
  } finally {
    releaseLocalStoreLock(transitionLock);
  }
}

/** Verify one receipt without creating a key or filesystem state. */
export function verifyAgentOsObserverAttemptReceiptV1(
  value: unknown,
  dependencies: AgentOsObserverAttemptStoreDependenciesV1 | null =
    defaultAgentOsObserverAttemptStoreDependenciesV1('read'),
): AgentOsObserverAttemptReceiptV1 | null {
  if (!dependencies || !validDependencies(dependencies) || !dependencies.key) return null;
  return reconstructWithKey(value, dependencies.key);
}
