import * as path from 'node:path';

const DISPOSABLE_TASK_NAME = /^AshlrM93Integration-[a-f0-9-]{1,72}$/;
const MAX_WINDOWS_TASK_XML_BYTES = 256 * 1024;
const MAX_WINDOWS_TASK_SECURITY_DESCRIPTOR_BYTES = 64 * 1024;

function assertSupportedTaskName(taskName: string): void {
  if (taskName !== 'AshlrDaemon' && !DISPOSABLE_TASK_NAME.test(taskName)) {
    throw new Error('unsupported Task Scheduler task name');
  }
}

export function windowsPowerShellPath(
  environment: NodeJS.ProcessEnv = process.env,
): string {
  const systemRoot = environment.SystemRoot ?? environment.WINDIR ?? String.raw`C:\Windows`;
  const normalizedRoot = path.win32.normalize(systemRoot);
  if (
    !/^[A-Za-z]:\\/.test(normalizedRoot) ||
    normalizedRoot.includes('\0') ||
    path.win32.resolve(normalizedRoot) !== normalizedRoot
  ) {
    throw new Error('Windows SystemRoot is not a canonical local absolute path');
  }
  return path.win32.join(
    normalizedRoot,
    'System32',
    'WindowsPowerShell',
    'v1.0',
    'powershell.exe',
  );
}

export const WINDOWS_TASK_DEFINITION_VALIDATION_SCRIPT = [
  "function Get-AshlrElementPath($node){$parts=New-Object 'System.Collections.Generic.List[string]'",
  '$cursor=$node',
  "while($null -ne $cursor -and $cursor.NodeType -eq [Xml.XmlNodeType]::Element){$parts.Insert(0,[string]$cursor.LocalName);$cursor=$cursor.ParentNode}",
  "return '/' + ($parts -join '/')}",
  "function Get-AshlrOne($document,$namespaceManager,[string]$xpath,[string]$label){$nodes=@($document.SelectNodes($xpath,$namespaceManager));if($nodes.Count -ne 1){throw ($label + ' must appear exactly once')};return $nodes[0]}",
  'function Assert-AshlrTaskXmlText([string]$xmlText,[string]$expectedTaskName){',
  `if([Text.Encoding]::UTF8.GetByteCount($xmlText) -gt ${MAX_WINDOWS_TASK_XML_BYTES}){throw 'task XML exceeds size limit'}`,
  '$readerSettings=New-Object Xml.XmlReaderSettings',
  '$readerSettings.DtdProcessing=[Xml.DtdProcessing]::Prohibit',
  '$readerSettings.XmlResolver=$null',
  `$readerSettings.MaxCharactersInDocument=${MAX_WINDOWS_TASK_XML_BYTES}`,
  '$stringReader=[IO.StringReader]::new($xmlText)',
  '$reader=[Xml.XmlReader]::Create($stringReader,$readerSettings)',
  '$document=New-Object Xml.XmlDocument',
  '$document.PreserveWhitespace=$false',
  '$document.XmlResolver=$null',
  'try{$document.Load($reader)}finally{$reader.Dispose();$stringReader.Dispose()}',
  "foreach($candidate in @($document.SelectNodes('//node()'))){if($candidate.NodeType -in @([Xml.XmlNodeType]::Comment,[Xml.XmlNodeType]::ProcessingInstruction,[Xml.XmlNodeType]::DocumentType,[Xml.XmlNodeType]::CDATA)){throw 'unsupported task XML node type'};if($candidate.NodeType -eq [Xml.XmlNodeType]::Text -and @($candidate.ParentNode.ChildNodes|Where-Object{$_.NodeType -eq [Xml.XmlNodeType]::Element}).Count -gt 0 -and -not [string]::IsNullOrWhiteSpace([string]$candidate.Value)){throw 'task XML contains mixed content'}}",
  "$taskNamespace='http://schemas.microsoft.com/windows/2004/02/mit/task'",
  "if($document.DocumentElement.LocalName -cne 'Task' -or $document.DocumentElement.NamespaceURI -cne $taskNamespace){throw 'unsupported task XML root'}",
  '$allowedPaths=@{}',
  "@('/Task','/Task/RegistrationInfo','/Task/RegistrationInfo/Date','/Task/RegistrationInfo/Author','/Task/RegistrationInfo/URI','/Task/RegistrationInfo/SecurityDescriptor','/Task/Triggers','/Task/Triggers/LogonTrigger','/Task/Triggers/LogonTrigger/Enabled','/Task/Triggers/LogonTrigger/UserId','/Task/Triggers/LogonTrigger/ExecutionTimeLimit','/Task/Principals','/Task/Principals/Principal','/Task/Principals/Principal/UserId','/Task/Principals/Principal/LogonType','/Task/Principals/Principal/RunLevel','/Task/Settings','/Task/Settings/AllowStartOnDemand','/Task/Settings/MultipleInstancesPolicy','/Task/Settings/DisallowStartIfOnBatteries','/Task/Settings/StopIfGoingOnBatteries','/Task/Settings/AllowHardTerminate','/Task/Settings/StartWhenAvailable','/Task/Settings/RunOnlyIfNetworkAvailable','/Task/Settings/WakeToRun','/Task/Settings/Enabled','/Task/Settings/Hidden','/Task/Settings/ExecutionTimeLimit','/Task/Settings/Priority','/Task/Settings/RunOnlyIfIdle','/Task/Settings/UseUnifiedSchedulingEngine','/Task/Settings/DisallowStartOnRemoteAppSession','/Task/Settings/Compatibility','/Task/Settings/IdleSettings','/Task/Settings/IdleSettings/Duration','/Task/Settings/IdleSettings/WaitTimeout','/Task/Settings/IdleSettings/StopOnIdleEnd','/Task/Settings/IdleSettings/RestartOnIdle','/Task/Actions','/Task/Actions/Exec','/Task/Actions/Exec/Command')|ForEach-Object{$allowedPaths[$_]=$true}",
  '$pathCounts=@{}',
  "foreach($node in @($document.SelectNodes('//*'))){$nodePath=Get-AshlrElementPath $node",
  "if($node.NamespaceURI -cne $taskNamespace -or -not $allowedPaths.ContainsKey($nodePath)){throw ('unsupported task XML element ' + $nodePath)}",
  '$pathCounts[$nodePath]=1+[int]$pathCounts[$nodePath]',
  "if($pathCounts[$nodePath] -gt 1){throw ('duplicate task XML element ' + $nodePath)}",
  'foreach($attribute in @($node.Attributes)){',
  "if($attribute.Name -ceq 'xmlns' -or $attribute.Prefix -ceq 'xmlns'){continue}",
  "$attributePath=$nodePath + '/@' + $attribute.LocalName",
  "if($attributePath -notin @('/Task/@version','/Task/Principals/Principal/@id','/Task/Actions/@Context')){throw ('unsupported task XML attribute ' + $attributePath)}}}",
  "$namespaceManager=[Xml.XmlNamespaceManager]::new($document.NameTable)",
  "$namespaceManager.AddNamespace('t',$taskNamespace)",
  "$version=[string]$document.DocumentElement.GetAttribute('version')",
  "if($version -notin @('1.2','1.3','1.4')){throw 'unsupported task XML version'}",
  "$principalNode=Get-AshlrOne $document $namespaceManager '/t:Task/t:Principals/t:Principal' 'task principal'",
  "$actionsNode=Get-AshlrOne $document $namespaceManager '/t:Task/t:Actions' 'task actions'",
  "[void](Get-AshlrOne $document $namespaceManager '/t:Task/t:Triggers/t:LogonTrigger' 'task logon trigger')",
  "[void](Get-AshlrOne $document $namespaceManager '/t:Task/t:Actions/t:Exec/t:Command' 'task command')",
  "[void](Get-AshlrOne $document $namespaceManager '/t:Task/t:Settings' 'task settings')",
  "$principalId=[string]$principalNode.GetAttribute('id')",
  "$actionContext=[string]$actionsNode.GetAttribute('Context')",
  "if([string]::IsNullOrEmpty($principalId) -or $principalId -cne 'AshlrPrincipal' -or $actionContext -cne $principalId){throw 'task XML principal context is not exact'}",
  "$triggerLimit=Get-AshlrOne $document $namespaceManager '/t:Task/t:Triggers/t:LogonTrigger/t:ExecutionTimeLimit' 'trigger execution limit'",
  "$taskLimit=Get-AshlrOne $document $namespaceManager '/t:Task/t:Settings/t:ExecutionTimeLimit' 'task execution limit'",
  "$allowDemand=Get-AshlrOne $document $namespaceManager '/t:Task/t:Settings/t:AllowStartOnDemand' 'task demand-start setting'",
  "$multipleInstances=Get-AshlrOne $document $namespaceManager '/t:Task/t:Settings/t:MultipleInstancesPolicy' 'task multiple-instance setting'",
  "$idleDuration=Get-AshlrOne $document $namespaceManager '/t:Task/t:Settings/t:IdleSettings/t:Duration' 'task idle duration'",
  "$idleWaitTimeout=Get-AshlrOne $document $namespaceManager '/t:Task/t:Settings/t:IdleSettings/t:WaitTimeout' 'task idle wait timeout'",
  "$registrationSecurity=Get-AshlrOne $document $namespaceManager '/t:Task/t:RegistrationInfo/t:SecurityDescriptor' 'task registration security descriptor'",
  "if([string]$triggerLimit.InnerText -cne 'PT0S'){throw 'task logon trigger execution limit is not unlimited'}",
  "if([string]$taskLimit.InnerText -cne 'PT0S'){throw 'task execution limit is not unlimited'}",
  "if([string]$allowDemand.InnerText -cne 'true'){throw 'task demand start is not enabled'}",
  "if([string]$multipleInstances.InnerText -cne 'IgnoreNew'){throw 'task multiple-instance policy is not IgnoreNew'}",
  "if([string]$idleDuration.InnerText -cne 'PT10M' -or [string]$idleWaitTimeout.InnerText -cne 'PT1H'){throw 'task idle defaults are not exact'}",
  'Assert-AshlrTaskSecurityDescriptor ([string]$registrationSecurity.InnerText)',
  "$authorNodes=@($document.SelectNodes('/t:Task/t:RegistrationInfo/t:Author',$namespaceManager))",
  "if($authorNodes.Count -eq 1){$author=[string]$authorNodes[0].InnerText;try{$authorSid=([Security.Principal.SecurityIdentifier]$author).Value}catch{$authorSid=([Security.Principal.NTAccount]$author).Translate([Security.Principal.SecurityIdentifier]).Value};if($authorSid -cne [Security.Principal.WindowsIdentity]::GetCurrent().User.Value){throw 'task XML author is not the current user'}}",
  "$uriNodes=@($document.SelectNodes('/t:Task/t:RegistrationInfo/t:URI',$namespaceManager))",
  "if($uriNodes.Count -eq 1 -and [string]$uriNodes[0].InnerText -cne ('\\'+$expectedTaskName)){throw 'task XML URI is not exact'}}",
  'function Assert-AshlrTaskXml($definition,[string]$expectedTaskName){Assert-AshlrTaskXmlText ([string]$definition.XmlText) $expectedTaskName}',
  'function Assert-AshlrTaskDefinition($definition,[string]$expectedLauncher,[string]$expectedTaskName){$actions=$definition.Actions',
  "if($actions.Count -ne 1){throw 'unsupported task action schema'}",
  '$action=$actions.Item(1)',
  "if([int]$action.Type -ne 0){throw 'unsupported task action schema'}",
  '$actualLauncher=[string]$action.Path',
  "if($actualLauncher -cne $actualLauncher.Trim()){throw 'task action path is not canonical'}",
  '$normalizedLauncher=[IO.Path]::GetFullPath($actualLauncher)',
  "if(-not [string]::Equals($actualLauncher,$normalizedLauncher,[StringComparison]::OrdinalIgnoreCase)){throw 'task action path is not fully qualified'}",
  "if(-not [string]::Equals($actualLauncher,$expectedLauncher,[StringComparison]::OrdinalIgnoreCase)){throw 'task action does not match trusted Ashlr launcher'}",
  "if(-not [string]::IsNullOrEmpty([string]$action.Arguments)){throw 'task action arguments are not supported'}",
  "if(-not [string]::IsNullOrEmpty([string]$action.WorkingDirectory)){throw 'task action working directory is not supported'}",
  '$triggers=$definition.Triggers',
  "if($triggers.Count -ne 1){throw 'unsupported task trigger schema'}",
  '$trigger=$triggers.Item(1)',
  "if([int]$trigger.Type -ne 9 -or -not [bool]$trigger.Enabled){throw 'unsupported task trigger schema'}",
  '$current=[Security.Principal.WindowsIdentity]::GetCurrent()',
  '$triggerUserId=[string]$trigger.UserId',
  "try{$triggerSid=([Security.Principal.SecurityIdentifier]$triggerUserId).Value}catch{$triggerSid=([Security.Principal.NTAccount]$triggerUserId).Translate([Security.Principal.SecurityIdentifier]).Value}",
  "if(-not [string]::Equals($triggerSid,$current.User.Value,[StringComparison]::OrdinalIgnoreCase)){throw 'task logon trigger is not scoped to the current user'}",
  "if(-not [string]::IsNullOrEmpty([string]$trigger.Delay) -or -not [string]::IsNullOrEmpty([string]$trigger.StartBoundary) -or -not [string]::IsNullOrEmpty([string]$trigger.EndBoundary) -or [string]$trigger.ExecutionTimeLimit -cne 'PT0S'){throw 'task logon trigger timing is not supported'}",
  '$repetition=$trigger.Repetition',
  "if(-not [string]::IsNullOrEmpty([string]$repetition.Interval) -or -not [string]::IsNullOrEmpty([string]$repetition.Duration) -or [bool]$repetition.StopAtDurationEnd){throw 'task trigger repetition is not supported'}",
  '$principal=$definition.Principal',
  "if([int]$principal.RunLevel -ne 0){throw 'task must run with limited privileges'}",
  "if([int]$principal.LogonType -ne 3){throw 'unsupported task logon type cannot be recovered'}",
  "if(-not [string]::IsNullOrEmpty([string]$principal.GroupId)){throw 'task group principal is not supported'}",
  '$principalId=[string]$principal.UserId',
  "try{$principalSid=([Security.Principal.SecurityIdentifier]$principalId).Value}catch{$principalSid=([Security.Principal.NTAccount]$principalId).Translate([Security.Principal.SecurityIdentifier]).Value}",
  "if(-not [string]::Equals($principalSid,$current.User.Value,[StringComparison]::OrdinalIgnoreCase)){throw 'task principal is not the current user'}",
  '$settings=$definition.Settings',
  "if(-not [bool]$settings.Enabled -or [bool]$settings.Hidden -or [bool]$settings.WakeToRun -or [bool]$settings.StartWhenAvailable -or [int]$settings.RestartCount -ne 0 -or -not [bool]$settings.AllowDemandStart -or [int]$settings.MultipleInstances -ne 2 -or [string]$settings.ExecutionTimeLimit -cne 'PT0S' -or [bool]$settings.RunOnlyIfIdle -or [bool]$settings.RunOnlyIfNetworkAvailable -or [bool]$settings.DisallowStartIfOnBatteries -or [bool]$settings.StopIfGoingOnBatteries -or -not [bool]$settings.AllowHardTerminate -or [int]$settings.Priority -ne 7 -or [int]$settings.Compatibility -ne 2 -or [string]$settings.IdleSettings.IdleDuration -cne 'PT10M' -or [string]$settings.IdleSettings.WaitTimeout -cne 'PT1H' -or -not [bool]$settings.IdleSettings.StopOnIdleEnd -or [bool]$settings.IdleSettings.RestartOnIdle){throw 'unsupported task settings'}",
  'Assert-AshlrTaskXml $definition $expectedTaskName',
  '}',
].join(';');

export const WINDOWS_TASK_SECURITY_VALIDATION_SCRIPT = [
  'function Expand-AshlrTaskAccessMask([int]$accessMask){',
  '$bytes=[BitConverter]::GetBytes($accessMask)',
  '$mask=[uint64][BitConverter]::ToUInt32($bytes,0)',
  "if(($mask -band 0x80000000L) -ne 0){$mask=($mask -bxor 0x80000000L) -bor 0x00120089L}",
  "if(($mask -band 0x40000000L) -ne 0){$mask=($mask -bxor 0x40000000L) -bor 0x00120116L}",
  "if(($mask -band 0x20000000L) -ne 0){$mask=($mask -bxor 0x20000000L) -bor 0x001200A0L}",
  "if(($mask -band 0x10000000L) -ne 0){$mask=($mask -bxor 0x10000000L) -bor 0x001F01FFL}",
  'return [uint64]($mask -band 0xFFFFFFFFL)}',
  'function Assert-AshlrTaskSecurityDescriptor([string]$sddl){',
  "if([string]::IsNullOrWhiteSpace($sddl)){throw 'task security descriptor is empty'}",
  '$descriptor=[Security.AccessControl.RawSecurityDescriptor]::new($sddl)',
  '$currentSid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value',
  "$trustedSids=@($currentSid,'S-1-5-18','S-1-5-32-544')",
  "if($null -eq $descriptor.Owner -or $trustedSids -cnotcontains $descriptor.Owner.Value){throw 'task owner is not trusted'}",
  '$flags=$descriptor.ControlFlags',
  "if($null -eq $descriptor.DiscretionaryAcl -or $descriptor.DiscretionaryAcl.Count -eq 0 -or ($flags -band [Security.AccessControl.ControlFlags]::DiscretionaryAclPresent) -eq 0 -or ($flags -band [Security.AccessControl.ControlFlags]::DiscretionaryAclProtected) -eq 0){throw 'task DACL is null, empty, or inheritable'}",
  '$common=[Security.AccessControl.CommonSecurityDescriptor]::new($false,$false,$descriptor)',
  "if(-not $common.DiscretionaryAcl.IsCanonical){throw 'task DACL is not canonical'}",
  '$safeUntrusted=[uint64]0x001200A9',
  '$currentCanControl=$false',
  '$systemCanAccess=$false',
  'for($index=0;$index -lt $descriptor.DiscretionaryAcl.Count;$index++){',
  '$ace=$descriptor.DiscretionaryAcl[$index]',
  "if(-not ($ace -is [Security.AccessControl.CommonAce]) -or $ace.IsCallback){throw 'unsupported task DACL ACE'}",
  "$sid=$ace.SecurityIdentifier.Value",
  "if($ace.AceQualifier -eq [Security.AccessControl.AceQualifier]::AccessDenied){throw 'task DACL deny ACE is not supported'}",
  "if($ace.AceQualifier -ne [Security.AccessControl.AceQualifier]::AccessAllowed){throw 'unsupported task DACL ACE qualifier'}",
  '$mask=Expand-AshlrTaskAccessMask $ace.AccessMask',
  '$unsafe=$mask -band ([uint64]0xFFFFFFFFL -bxor $safeUntrusted)',
  "if($trustedSids -cnotcontains $sid -and $unsafe -ne 0){throw 'untrusted identity can modify the task'}",
  "if($sid -ceq $currentSid -and $unsafe -ne 0){$currentCanControl=$true}",
  "if($sid -ceq 'S-1-5-18' -and $mask -ne 0){$systemCanAccess=$true}}",
  "if(-not $currentCanControl){throw 'current user cannot control the task'}",
  "if(-not $systemCanAccess){throw 'LOCAL SYSTEM cannot access the task'}",
  '}',
  'function Get-AshlrTaskSecurityFingerprint([string]$sddl){',
  '$descriptor=[Security.AccessControl.RawSecurityDescriptor]::new($sddl)',
  '$bytes=New-Object byte[] $descriptor.BinaryLength',
  '$descriptor.GetBinaryForm($bytes,0)',
  'return [Convert]::ToBase64String($bytes)}',
  'function Assert-AshlrTaskSecurityBinding($definition,[string]$sddl){',
  '$embedded=[string]$definition.RegistrationInfo.SecurityDescriptor',
  'Assert-AshlrTaskSecurityDescriptor $embedded',
  'Assert-AshlrTaskSecurityDescriptor $sddl',
  "if((Get-AshlrTaskSecurityFingerprint $embedded) -cne (Get-AshlrTaskSecurityFingerprint $sddl)){throw 'task XML security descriptor conflicts with registered DACL'}}",
].join(';');

const WINDOWS_TASK_DIGEST_SCRIPT = [
  'function Get-Sha256Hex([byte[]]$bytes){$sha=[Security.Cryptography.SHA256]::Create()',
  "try{return ([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}",
].join(';');

export function buildWindowsTaskCreateScript(taskName: string): string {
  assertSupportedTaskName(taskName);
  return [
    "$ErrorActionPreference='Stop'",
    WINDOWS_TASK_DEFINITION_VALIDATION_SCRIPT,
    WINDOWS_TASK_SECURITY_VALIDATION_SCRIPT,
    '$raw=[Console]::In.ReadToEnd()',
    '$request=$raw|ConvertFrom-Json',
    '$keys=@($request.PSObject.Properties.Name|Sort-Object)',
    "if(($keys -join ',') -ne 'expectedLauncherPath'){throw 'invalid create request'}",
    '$expectedLauncher=[IO.Path]::GetFullPath([string]$request.expectedLauncherPath)',
    `$taskName='${taskName}'`,
    "$scheduler=New-Object -ComObject 'Schedule.Service'",
    '$scheduler.Connect()',
    "$folder=$scheduler.GetFolder('\\')",
    "$definition=$scheduler.NewTask(0)",
    '$current=[Security.Principal.WindowsIdentity]::GetCurrent()',
    "$sddl='O:'+$current.User.Value+'G:SYD:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;'+$current.User.Value+')'",
    '$definition.RegistrationInfo.Author=$current.Name',
    "$definition.RegistrationInfo.URI='\\'+$taskName",
    '$definition.RegistrationInfo.SecurityDescriptor=$sddl',
    "$principal=$definition.Principal",
    "$principal.Id='AshlrPrincipal'",
    '$principal.UserId=$current.Name',
    '$principal.LogonType=3',
    '$principal.RunLevel=0',
    '$trigger=$definition.Triggers.Create(9)',
    '$trigger.Enabled=$true',
    '$trigger.UserId=$current.Name',
    "$trigger.ExecutionTimeLimit='PT0S'",
    '$action=$definition.Actions.Create(0)',
    '$action.Path=$expectedLauncher',
    "$definition.Actions.Context='AshlrPrincipal'",
    '$settings=$definition.Settings',
    '$settings.AllowDemandStart=$true',
    '$settings.MultipleInstances=2',
    '$settings.DisallowStartIfOnBatteries=$false',
    '$settings.StopIfGoingOnBatteries=$false',
    '$settings.AllowHardTerminate=$true',
    '$settings.StartWhenAvailable=$false',
    '$settings.RunOnlyIfNetworkAvailable=$false',
    '$settings.WakeToRun=$false',
    '$settings.Enabled=$true',
    '$settings.Hidden=$false',
    "$settings.ExecutionTimeLimit='PT0S'",
    '$settings.Priority=7',
    '$settings.Compatibility=2',
    '$settings.RunOnlyIfIdle=$false',
    '$settings.RestartCount=0',
    "$settings.IdleSettings.IdleDuration='PT10M'",
    "$settings.IdleSettings.WaitTimeout='PT1H'",
    '$settings.IdleSettings.StopOnIdleEnd=$true',
    '$settings.IdleSettings.RestartOnIdle=$false',
    'Assert-AshlrTaskDefinition $definition $expectedLauncher $taskName',
    'Assert-AshlrTaskSecurityBinding $definition $sddl',
    '$flags=2 -bor 16 -bor 32',
    '[void]$folder.RegisterTaskDefinition($taskName,$definition,$flags,$null,$null,3,$sddl)',
    '$registered=$folder.GetTask($taskName)',
    'Assert-AshlrTaskDefinition $registered.Definition $expectedLauncher $taskName',
    'Assert-AshlrTaskSecurityBinding $registered.Definition ([string]$registered.GetSecurityDescriptor(7))',
    "[Console]::Out.Write('created')",
  ].join(';');
}

export function buildWindowsTaskSnapshotScript(taskName: string): string {
  assertSupportedTaskName(taskName);
  return [
    "$ErrorActionPreference='Stop'",
    WINDOWS_TASK_DEFINITION_VALIDATION_SCRIPT,
    WINDOWS_TASK_SECURITY_VALIDATION_SCRIPT,
    '$raw=[Console]::In.ReadToEnd()',
    '$request=$raw|ConvertFrom-Json',
    '$keys=@($request.PSObject.Properties.Name|Sort-Object)',
    "if(($keys -join ',') -ne 'expectedLauncherPath'){throw 'invalid snapshot request'}",
    '$expectedLauncher=[IO.Path]::GetFullPath([string]$request.expectedLauncherPath)',
    `$taskName='${taskName}'`,
    "$scheduler=New-Object -ComObject 'Schedule.Service'",
    '$scheduler.Connect()',
    "$folder=$scheduler.GetFolder('\\')",
    "try{$registered=$folder.GetTask($taskName)}catch{if($_.Exception.HResult -eq -2147024894){[Console]::Out.Write('absent');exit 0};throw}",
    '$xml=[string]$registered.Xml',
    '$definition=$registered.Definition',
    '$sddl=[string]$registered.GetSecurityDescriptor(7)',
    'Assert-AshlrTaskDefinition $definition $expectedLauncher $taskName',
    'Assert-AshlrTaskSecurityBinding $definition $sddl',
    '$xmlBytes=[Text.Encoding]::UTF8.GetBytes($xml)',
    '$sddlBytes=[Text.Encoding]::UTF8.GetBytes($sddl)',
    `if($xmlBytes.Length -gt ${MAX_WINDOWS_TASK_XML_BYTES}){throw 'task XML exceeds size limit'}`,
    `if($sddlBytes.Length -gt ${MAX_WINDOWS_TASK_SECURITY_DESCRIPTOR_BYTES}){throw 'task security descriptor exceeds size limit'}`,
    '$snapshot=[ordered]@{}',
    "$snapshot.state=([int]$registered.State).ToString([Globalization.CultureInfo]::InvariantCulture)",
    '$snapshot.taskXmlBase64=[Convert]::ToBase64String($xmlBytes)',
    '$snapshot.taskSecurityDescriptorBase64=[Convert]::ToBase64String($sddlBytes)',
    '[Console]::Out.Write(($snapshot|ConvertTo-Json -Compress))',
  ].join(';');
}

export function buildWindowsTaskRestoreScript(taskName: string): string {
  assertSupportedTaskName(taskName);
  return [
    "$ErrorActionPreference='Stop'",
    WINDOWS_TASK_DEFINITION_VALIDATION_SCRIPT,
    WINDOWS_TASK_SECURITY_VALIDATION_SCRIPT,
    '$raw=[Console]::In.ReadToEnd()',
    '$request=$raw|ConvertFrom-Json',
    '$keys=@($request.PSObject.Properties.Name|Sort-Object)',
    "if(($keys -join ',') -ne 'expectedLauncherPath,taskSecurityDescriptorBase64,taskXmlBase64'){throw 'invalid restore request'}",
    '$expectedLauncher=[IO.Path]::GetFullPath([string]$request.expectedLauncherPath)',
    '$xml=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String([string]$request.taskXmlBase64))',
    '$sddl=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String([string]$request.taskSecurityDescriptorBase64))',
    `$taskName='${taskName}'`,
    'Assert-AshlrTaskXmlText $xml $taskName',
    "$scheduler=New-Object -ComObject 'Schedule.Service'",
    '$scheduler.Connect()',
    '$definition=$scheduler.NewTask(0)',
    '$definition.XmlText=$xml',
    'Assert-AshlrTaskDefinition $definition $expectedLauncher $taskName',
    'Assert-AshlrTaskSecurityBinding $definition $sddl',
    "$folder=$scheduler.GetFolder('\\')",
    '$flags=2 -bor 16 -bor 32',
    `[void]$folder.RegisterTask('${taskName}',$xml,$flags,$null,$null,0,$sddl)`,
    "[Console]::Out.Write('restored')",
  ].join(';');
}

export function buildWindowsTaskStopDeleteScript(taskName: string): string {
  assertSupportedTaskName(taskName);
  return [
    "$ErrorActionPreference='Stop'",
    WINDOWS_TASK_DEFINITION_VALIDATION_SCRIPT,
    WINDOWS_TASK_SECURITY_VALIDATION_SCRIPT,
    WINDOWS_TASK_DIGEST_SCRIPT,
    '$raw=[Console]::In.ReadToEnd()',
    '$request=$raw|ConvertFrom-Json',
    '$keys=@($request.PSObject.Properties.Name|Sort-Object)',
    "if(($keys -join ',') -ne 'expectedLauncherPath,taskSecurityDescriptorSha256,taskXmlSha256'){throw 'invalid removal request'}",
    '$expectedLauncher=[IO.Path]::GetFullPath([string]$request.expectedLauncherPath)',
    '$expectedXmlSha256=[string]$request.taskXmlSha256',
    '$expectedSecuritySha256=[string]$request.taskSecurityDescriptorSha256',
    "if($expectedXmlSha256 -cnotmatch '^[a-f0-9]{64}$' -or $expectedSecuritySha256 -cnotmatch '^[a-f0-9]{64}$'){throw 'invalid removal digest'}",
    `$taskName='${taskName}'`,
    "$scheduler=New-Object -ComObject 'Schedule.Service'",
    '$scheduler.Connect()',
    "$folder=$scheduler.GetFolder('\\')",
    "$registered=$folder.GetTask($taskName)",
    '$registeredSddl=[string]$registered.GetSecurityDescriptor(7)',
    'Assert-AshlrTaskDefinition $registered.Definition $expectedLauncher $taskName',
    'Assert-AshlrTaskSecurityBinding $registered.Definition $registeredSddl',
    '$xmlSha256=Get-Sha256Hex ([Text.Encoding]::UTF8.GetBytes([string]$registered.Xml))',
    '$securitySha256=Get-Sha256Hex ([Text.Encoding]::UTF8.GetBytes($registeredSddl))',
    "if($xmlSha256 -cne $expectedXmlSha256 -or $securitySha256 -cne $expectedSecuritySha256){throw 'task identity changed before removal'}",
    'if(@(2,4) -contains [int]$registered.State){$registered.Stop(0)',
    "for($attempt=0;$attempt -lt 50 -and @(2,4) -contains [int]$registered.State;$attempt++){Start-Sleep -Milliseconds 100}",
    "if(@(2,4) -contains [int]$registered.State){throw 'Task Scheduler could not prove task stopped before deletion'}}",
    '$current=$folder.GetTask($taskName)',
    '$currentSddl=[string]$current.GetSecurityDescriptor(7)',
    'Assert-AshlrTaskDefinition $current.Definition $expectedLauncher $taskName',
    'Assert-AshlrTaskSecurityBinding $current.Definition $currentSddl',
    '$currentXmlSha256=Get-Sha256Hex ([Text.Encoding]::UTF8.GetBytes([string]$current.Xml))',
    '$currentSecuritySha256=Get-Sha256Hex ([Text.Encoding]::UTF8.GetBytes($currentSddl))',
    "if($currentXmlSha256 -cne $expectedXmlSha256 -or $currentSecuritySha256 -cne $expectedSecuritySha256){throw 'task identity changed while stopping'}",
    '$folder.DeleteTask($taskName,0)',
    "try{[void]$folder.GetTask($taskName);throw 'task remained registered after deletion'}catch{if($_.Exception.Message -ceq 'task remained registered after deletion'){throw};if($_.Exception.HResult -ne -2147024894){throw}}",
    "[Console]::Out.Write('deleted')",
  ].join(';');
}

export function buildWindowsTaskRunScript(taskName: string): string {
  assertSupportedTaskName(taskName);
  return [
    "$ErrorActionPreference='Stop'",
    WINDOWS_TASK_DEFINITION_VALIDATION_SCRIPT,
    WINDOWS_TASK_SECURITY_VALIDATION_SCRIPT,
    '$raw=[Console]::In.ReadToEnd()',
    '$request=$raw|ConvertFrom-Json',
    '$keys=@($request.PSObject.Properties.Name|Sort-Object)',
    "if(($keys -join ',') -ne 'expectedLauncherPath'){throw 'invalid run request'}",
    '$expectedLauncher=[IO.Path]::GetFullPath([string]$request.expectedLauncherPath)',
    `$taskName='${taskName}'`,
    "$scheduler=New-Object -ComObject 'Schedule.Service'",
    '$scheduler.Connect()',
    "$registered=$scheduler.GetFolder('\\').GetTask($taskName)",
    "if([int]$registered.State -ne 3){throw 'Ashlr task is not uniquely ready'}",
    '$definition=$registered.Definition',
    '$sddl=[string]$registered.GetSecurityDescriptor(7)',
    'Assert-AshlrTaskDefinition $definition $expectedLauncher $taskName',
    'Assert-AshlrTaskSecurityBinding $definition $sddl',
    '[void]$registered.Run($null)',
    "[Console]::Out.Write('started')",
  ].join(';');
}

export const WINDOWS_TASK_CREATE_SCRIPT = buildWindowsTaskCreateScript('AshlrDaemon');
export const WINDOWS_TASK_SNAPSHOT_SCRIPT = buildWindowsTaskSnapshotScript('AshlrDaemon');
export const WINDOWS_TASK_RESTORE_SCRIPT = buildWindowsTaskRestoreScript('AshlrDaemon');
export const WINDOWS_TASK_STOP_DELETE_SCRIPT = buildWindowsTaskStopDeleteScript('AshlrDaemon');
export const WINDOWS_TASK_RUN_SCRIPT = buildWindowsTaskRunScript('AshlrDaemon');
