/**
 * cli/completions.ts — `ashlr completions zsh|bash` (M31).
 *
 * Emits a STATIC shell-completion script generated from the top-level command
 * table. Install:
 *   zsh:  ashlr completions zsh  > ~/.zsh/completions/_ashlr   (fpath dir)
 *   bash: ashlr completions bash > ~/.local/share/bash-completion/completions/ashlr
 *
 * Read-only: prints to stdout, writes nothing. Exit codes: 0 / 2 bad usage.
 */

import { makeColors, isTty } from './ui.js';

/** Top-level commands (kept in sync by test/m31.cli-agent.test.ts). */
export const TOP_LEVEL_COMMANDS: string[] = [
  'index', 'go', 'status', 'ls', 'open', 'tidy', 'config', 'doctor', 'init',
  'mcp', 'run', 'runs', 'pulse', 'new', 'ship', 'recall', 'learn', 'genome',
  'update', 'spec', 'swarm', 'swarms', 'tui', 'dash', 'serve', 'models',
  'gh', 'vercel', 'wire', 'notify', 'telemetry', 'sandbox', 'audit',
  'enroll', 'backlog', 'inbox', 'daemon', 'ask', 'knowledge', 'reflect',
  'health', 'goals', 'digest', 'seams', 'verify-safety', 'preflight',
  'onboard', 'demo', 'orient', 'docs', 'completions', 'plugins', 'x', 'help',
];

/** Subcommands per top-level command (first-position completion only). */
const SUBCOMMANDS: Record<string, string[]> = {
  config: ['get', 'set', 'path'],
  mcp: ['list', 'doctor', 'install'],
  run: ['show'],
  spec: ['new', 'list', 'show', 'refine'],
  swarm: ['show'],
  models: ['pull', 'start'],
  gh: ['pr', 'issue', 'ci'],
  vercel: ['ls', 'logs'],
  wire: ['claude', 'codex', 'cursor', 'all'],
  notify: ['test'],
  telemetry: ['status', 'test'],
  sandbox: ['list', 'diff', 'cleanup', 'gc'],
  enroll: ['add', 'remove', 'list', 'kill'],
  backlog: ['refresh'],
  inbox: ['show', 'approve', 'reject'],
  daemon: ['start', 'stop', 'status'],
  knowledge: ['build', 'impact', 'graph'],
  reflect: ['playbooks', 'propose'],
  health: ['propose'],
  goals: ['add', 'plan', 'advance', 'status', 'recover-stale'],
  seams: ['status'],
  completions: ['zsh', 'bash'],
  plugins: ['init', 'list', 'info', 'enable', 'disable'],
};

function zshScript(): string {
  const subcases = Object.entries(SUBCOMMANDS)
    .map(([cmd, subs]) => `      ${cmd}) _values 'subcommand' ${subs.map((s) => `'${s}'`).join(' ')} ;;`)
    .join('\n');
  return `#compdef ashlr
# ashlr zsh completions — generated by \`ashlr completions zsh\`.
_ashlr() {
  local -a _ashlr_cmds
  _ashlr_cmds=(${TOP_LEVEL_COMMANDS.map((c) => `'${c}'`).join(' ')})
  if (( CURRENT == 2 )); then
    _values 'ashlr command' "\${_ashlr_cmds[@]}"
  elif (( CURRENT == 3 )); then
    case "\${words[2]}" in
${subcases}
      *) _files ;;
    esac
  else
    _files
  fi
}
_ashlr "$@"
`;
}

function bashScript(): string {
  const subcases = Object.entries(SUBCOMMANDS)
    .map(([cmd, subs]) => `      ${cmd}) COMPREPLY=( $(compgen -W "${subs.join(' ')}" -- "$cur") ) ;;`)
    .join('\n');
  return `# ashlr bash completions — generated by \`ashlr completions bash\`.
_ashlr_completions() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${TOP_LEVEL_COMMANDS.join(' ')}" -- "$cur") )
    return 0
  fi
  if [ "$COMP_CWORD" -eq 2 ]; then
    case "\${COMP_WORDS[1]}" in
${subcases}
      *) COMPREPLY=() ;;
    esac
    return 0
  fi
  COMPREPLY=()
}
complete -F _ashlr_completions ashlr
`;
}

export async function cmdCompletions(args: string[]): Promise<number> {
  const shell = args[0];
  if (shell === 'zsh') {
    process.stdout.write(zshScript());
    return 0;
  }
  if (shell === 'bash') {
    process.stdout.write(bashScript());
    return 0;
  }
  const c = makeColors(isTty());
  console.log('');
  console.log(c.bold('  ashlr completions') + c.dim(' — shell completion scripts'));
  console.log('');
  console.log(`    ${c.cyan('ashlr completions zsh')}    ${c.dim('print zsh completion (_ashlr) to stdout')}`);
  console.log(`    ${c.cyan('ashlr completions bash')}   ${c.dim('print bash completion to stdout')}`);
  console.log('');
  return shell === undefined || shell === '--help' || shell === '-h' || shell === 'help' ? 0 : 2;
}

// ---------------------------------------------------------------------------
// "did you mean" (used by the dispatcher's unknown-command path)
// ---------------------------------------------------------------------------

/** Bounded Levenshtein distance (small strings only; zero-dep). */
function editDistance(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;
  let prev = Array.from({ length: n + 1 }, (_v, j) => j);
  for (let i = 1; i <= m; i++) {
    const cur = [i, ...new Array<number>(n).fill(0)];
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      cur[j] = Math.min((cur[j - 1] ?? 0) + 1, (prev[j] ?? 0) + 1, (prev[j - 1] ?? 0) + cost);
    }
    prev = cur;
  }
  return prev[n] ?? 0;
}

/**
 * Closest known command for a typo, or null when nothing is plausibly close
 * (distance must be ≤ 2 and less than half the input length).
 */
export function didYouMean(input: string): string | null {
  let best: string | null = null;
  let bestDist = Infinity;
  for (const cmd of TOP_LEVEL_COMMANDS) {
    const d = editDistance(input.toLowerCase(), cmd);
    if (d < bestDist) {
      bestDist = d;
      best = cmd;
    }
  }
  if (best !== null && bestDist <= 2 && bestDist < Math.max(2, input.length / 2) + 1) {
    return best;
  }
  return null;
}
