/**
 * The Anthropic proxy's launch agent — what makes the lane survive a reboot.
 *
 * ## Why a second job rather than a flag on the first
 *
 * `launchd.ts` supervises llama-server through a shim that `exec`s it, so
 * launchd watches llama-server's own pid. That is the right shape and it has
 * exactly one slot: a launchd job supervises ONE process. The proxy is a
 * second process with an independent failure mode — it can be restarted for a
 * port change while llama-server, which takes minutes to load 27B of weights,
 * keeps serving. Folding them into one job would mean every proxy restart
 * dropped the model.
 *
 * ## Why the invocation is frozen at install time
 *
 * The shim records the exact argv resolved by `anthropicProxyHostArgv`, which
 * reads THIS INSTALL's module location — not `process.argv[1]`, and not
 * anything about the process that runs later. Freezing it has two properties
 * that matter:
 *
 *   1. launchd needs a command it can run with no hub process alive to ask.
 *   2. The resolution can be VERIFIED at install time, by starting it and
 *      probing the port, instead of failing at 3am at the next login. An
 *      install that cannot bind is reported as a failed install.
 *
 * The environment block carries host, port and upstream for the same reason
 * the spawn path does: it is the one channel whose shape is identical in every
 * runtime. See `anthropicProxyHostEnvironment`.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { escapeXml, shQuote } from './launchd.js';
import type { LaunchAgentMutation } from './launchd.js';
import {
  ANTHROPIC_PROXY_LAUNCH_AGENT_LABEL,
  anthropicProxyPlistPath,
  anthropicProxyShimPath,
  anthropicProxyStderrLogPath,
  anthropicProxyStdoutLogPath,
  localRuntimeDir,
  logsDir,
} from './paths.js';

/** Everything the proxy job needs. Kept explicit so generation stays pure. */
export interface AnthropicProxyAgentSpec {
  /** argv[0] — the interpreter or binary that runs the host. */
  command: string;
  /** argv after argv[0], exactly as `anthropicProxyHostArgv` resolved it. */
  args: readonly string[];
  /** Bind host for the proxy, after the loopback gate. */
  host: string;
  /** Port the proxy listens on. */
  port: number;
  /** Port llama-server listens on, i.e. the forward target. */
  upstreamPort: number;
  workingDirectory: string;
  stdoutLog: string;
  stderrLog: string;
}

/**
 * Render the shim the launch agent executes.
 *
 * `exec` replaces the shell so launchd supervises the host's OWN pid rather
 * than a shell wrapper — the same reason `buildLaunchAgentShim` does it.
 * Every value goes through {@link shQuote}; nothing is interpolated unquoted.
 *
 * PURE — string in, string out — so the exact script is pinned by unit tests.
 */
export function buildAnthropicProxyShim(spec: AnthropicProxyAgentSpec): string {
  const argv = [spec.command, ...spec.args].map(shQuote).join(' ');
  return `#!/bin/sh
# Generated by \`ashlr local-runtime install\`. Do not edit — reinstall instead.
# Removed by \`ashlr local-runtime uninstall\`.
set -u

# Host, proxy port and upstream port travel in the environment because the
# shipping runtimes disagree about argv offsets and \`node --eval\` refuses a
# trailing operand tail. config.ts reads exactly these three names.
ASHLR_LOCAL_RUNTIME_HOST=${shQuote(spec.host)}
ASHLR_LOCAL_RUNTIME_ANTHROPIC_PORT=${shQuote(String(spec.port))}
ASHLR_LOCAL_RUNTIME_PORT=${shQuote(String(spec.upstreamPort))}
export ASHLR_LOCAL_RUNTIME_HOST ASHLR_LOCAL_RUNTIME_ANTHROPIC_PORT ASHLR_LOCAL_RUNTIME_PORT

exec ${argv}
`;
}

/**
 * Render the proxy's plist.
 *
 * `KeepAlive` is unconditional, matching the llama-server job: the point is
 * that the lane is ALWAYS reachable, so a clean exit is as much a reason to
 * restart as a crash. PURE, so the XML is pinned by unit tests.
 */
export function buildAnthropicProxyPlist(
  spec: AnthropicProxyAgentSpec,
  shimPath: string = anthropicProxyShimPath(),
): string {
  const programArguments = ['/bin/sh', shimPath]
    .map((arg) => `      <string>${escapeXml(arg)}</string>`)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>${escapeXml(ANTHROPIC_PROXY_LAUNCH_AGENT_LABEL)}</string>
    <key>ProgramArguments</key>
    <array>
${programArguments}
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>ProcessType</key>
    <string>Background</string>
    <key>WorkingDirectory</key>
    <string>${escapeXml(spec.workingDirectory)}</string>
    <key>StandardOutPath</key>
    <string>${escapeXml(spec.stdoutLog)}</string>
    <key>StandardErrorPath</key>
    <string>${escapeXml(spec.stderrLog)}</string>
  </dict>
</plist>
`;
}

/** `gui/<uid>` — the per-user launchd domain. */
function guiDomain(): string {
  const uid = typeof process.getuid === 'function' ? process.getuid() : 0;
  return `gui/${uid}`;
}

/** Run launchctl, returning stdout, or null on any failure. Never throws. */
function launchctl(args: string[]): string | null {
  if (process.platform !== 'darwin') return null;
  try {
    return execFileSync('/bin/launchctl', args, {
      encoding: 'utf8',
      timeout: 15_000,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } catch {
    return null;
  }
}

/** Is the proxy plist present in ~/Library/LaunchAgents? Never throws. */
export function anthropicProxyAgentInstalled(path = anthropicProxyPlistPath()): boolean {
  try {
    return existsSync(path);
  } catch {
    return false;
  }
}

/** Is the proxy job currently bootstrapped into launchd? */
export function anthropicProxyAgentLoaded(): boolean {
  if (process.platform !== 'darwin') return false;
  return launchctl(['print', `${guiDomain()}/${ANTHROPIC_PROXY_LAUNCH_AGENT_LABEL}`]) !== null;
}

/**
 * Write the proxy plist and bootstrap the job.
 *
 * The write is reported even when `launchctl` refuses, so a partially-applied
 * install is visible rather than silent — the same contract as
 * {@link import('./launchd.js').installLaunchAgent}.
 */
export function installAnthropicProxyAgent(spec: AnthropicProxyAgentSpec): LaunchAgentMutation {
  const plistPath = anthropicProxyPlistPath();

  if (process.platform !== 'darwin') {
    return {
      ok: false,
      plistPath,
      loaded: false,
      detail: 'launch agents are a macOS facility; this platform has no equivalent here',
    };
  }

  const shimPath = anthropicProxyShimPath();
  try {
    mkdirSync(dirname(plistPath), { recursive: true });
    mkdirSync(logsDir(), { recursive: true, mode: 0o700 });
    mkdirSync(localRuntimeDir(), { recursive: true, mode: 0o700 });
    // Owner-only: the shim names an absolute interpreter and `exec`s it at
    // every login, so a world-writable copy is a standing privilege-escalation
    // path into a KeepAlive job.
    writeFileSync(shimPath, buildAnthropicProxyShim(spec), { mode: 0o700 });
    writeFileSync(plistPath, buildAnthropicProxyPlist(spec, shimPath), { mode: 0o644 });
  } catch (err: unknown) {
    return {
      ok: false,
      plistPath,
      loaded: false,
      detail: `could not write the Anthropic proxy launch agent: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  launchctl(['bootout', `${guiDomain()}/${ANTHROPIC_PROXY_LAUNCH_AGENT_LABEL}`]);
  const bootstrapped = launchctl(['bootstrap', guiDomain(), plistPath]) !== null;
  if (bootstrapped) launchctl(['enable', `${guiDomain()}/${ANTHROPIC_PROXY_LAUNCH_AGENT_LABEL}`]);

  const loaded = bootstrapped && anthropicProxyAgentLoaded();
  return {
    ok: true,
    plistPath,
    loaded,
    detail: loaded
      ? 'Anthropic proxy launch agent written and bootstrapped; the lane now starts at login and restarts on crash'
      : 'Anthropic proxy launch agent written, but launchctl did not bootstrap it — it will still load at next login',
  };
}

/** Boot the proxy job out and delete its plist. Idempotent; never throws. */
export function uninstallAnthropicProxyAgent(): LaunchAgentMutation {
  const plistPath = anthropicProxyPlistPath();
  const wasInstalled = anthropicProxyAgentInstalled(plistPath);

  launchctl(['bootout', `${guiDomain()}/${ANTHROPIC_PROXY_LAUNCH_AGENT_LABEL}`]);

  try {
    rmSync(plistPath, { force: true });
    rmSync(anthropicProxyShimPath(), { force: true });
  } catch (err: unknown) {
    return {
      ok: false,
      plistPath,
      loaded: anthropicProxyAgentLoaded(),
      detail: `could not remove the proxy plist: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  return {
    ok: true,
    plistPath,
    loaded: false,
    detail: wasInstalled
      ? 'Anthropic proxy launch agent booted out and removed'
      : 'no Anthropic proxy launch agent was installed; nothing to remove',
  };
}

/** Default proxy log paths, so callers do not reach into paths.ts. */
export function anthropicProxyLogPaths(): { stdout: string; stderr: string } {
  return { stdout: anthropicProxyStdoutLogPath(), stderr: anthropicProxyStderrLogPath() };
}
