/**
 * wiki/types.ts — shared shapes for the private repo wiki (3.15).
 *
 * The wiki is DeepWiki-shaped (per-repo architecture pages with file:line
 * citations, plus an Ask over them) but lives entirely on this machine:
 * pages are stored under ~/.ashlr/knowledge/wiki/<repo-key>/ and generated by
 * local models (or Grok, only where the repo allows remote engines).
 *
 * These types are also mirrored by the Verse web client (src/web-ui), so they
 * stay plain JSON — no Maps, Dates or class instances.
 */

/** Bumped whenever page rendering/prompting changes enough to invalidate every stored page. */
export const WIKI_GENERATOR_VERSION = 1;

/** A verified pointer into the repo: repo-relative path and a 1-based line span. */
export interface WikiCitation {
  file: string;
  line: number;
  endLine?: number;
}

export type WikiPageKind =
  | 'overview'
  | 'modules'
  | 'flows'
  | 'data'
  | 'commands'
  | 'change'
  | 'custom';

/** A planned page — what to generate and from which inputs. */
export interface WikiPageSpec {
  /** Stable slug, unique within the repo (e.g. `overview`, `change-src-core-run`). */
  id: string;
  title: string;
  kind: WikiPageKind;
  /** One-sentence goal of the page; fed to the model and shown under the title. */
  purpose: string;
  /** Parent page id for the tree (undefined = top level). */
  parent?: string;
  /** Repo-relative files whose contents feed this page (bounded). */
  inputs: string[];
  /** Pseudo-inputs that change the page without a file changing (`@tree`, `@steering`). */
  pseudo: string[];
  /** For `change`/`custom` pages: the module or focus area the page is about. */
  focus?: string;
  /** Per-page steering notes (from `.devin/wiki.json` page_notes or `.ashlr/wiki.json`). */
  notes: string[];
}

/** One stored page's metadata, kept in the repo manifest. */
export interface WikiPageMeta {
  id: string;
  title: string;
  kind: WikiPageKind;
  purpose: string;
  parent?: string;
  /** sha256 of the spec's static parts (title, purpose, focus, notes, generator version). */
  specHash: string;
  /** sha256 over specHash, input blob ids and pseudo-inputs. Equal hash == fresh. */
  inputHash: string;
  /** The inputs the hash covered — lets `status` re-hash without re-planning. */
  inputs: string[];
  pseudo: string[];
  /** Commit the page was generated at (null outside git). */
  commit: string | null;
  generatedAt: string;
  /** `facts-only` when no model was allowed/available; otherwise the engine:model used. */
  model: string;
  citations: number;
  /** Citations the model produced that did not verify and were removed. */
  droppedCitations: number;
}

export interface WikiManifest {
  version: 1;
  generator: number;
  repo: string;
  repoName: string;
  key: string;
  /** HEAD at the most recent build (null outside git). */
  commit: string | null;
  generatedAt: string;
  /** Hash of the steering files at the most recent build. */
  steeringHash: string;
  pages: WikiPageMeta[];
  /** Planned pages that were NOT generated (budget or failure) at the last build. */
  pending: string[];
  lastRun?: WikiRunSummary;
}

export interface WikiRunSummary {
  startedAt: string;
  finishedAt: string;
  generated: number;
  skippedFresh: number;
  deferred: number;
  failed: number;
  estimatedTokens: number;
  engine: string;
  budgetStop: 'pages' | 'tokens' | null;
  /** Why the run chose facts-only (no model), if it did. */
  modelNote?: string;
}

/** Freshness of the stored wiki against the repo as it is now. */
export interface WikiStatus {
  repo: string;
  repoName: string;
  key: string;
  exists: boolean;
  generatedAt: string | null;
  generatedCommit: string | null;
  currentCommit: string | null;
  pages: Array<{ id: string; title: string; kind: WikiPageKind; parent?: string; stale: boolean; model: string; generatedAt: string }>;
  stalePages: number;
  pendingPages: number;
  lastRun?: WikiRunSummary;
}

/** Verse route family (src/core/verse/wiki-api.ts). */
export const VERSE_WIKI_PATH = '/api/verse/wiki';

/** GET /api/verse/wiki */
export interface WikiReposView {
  repos: Array<{
    key: string;
    repo: string;
    name: string;
    exists: boolean;
    generatedAt: string | null;
    commit: string | null;
    pages: number;
    pending: number;
    building: boolean;
  }>;
}

/** A background build as the UI sees it. */
export interface WikiJobView {
  state: 'running' | 'done' | 'failed';
  startedAt: string;
  finishedAt: string | null;
  progress: { index: number; total: number; page: string | null };
  summary: WikiRunSummary | null;
  error: string | null;
  trigger: 'operator' | 'auto';
}

/** GET /api/verse/wiki/repo/<key> */
export interface WikiRepoView {
  status: WikiStatus;
  job: WikiJobView | null;
  /** `https://github.com/<owner>/<name>` when origin is on GitHub, else null. */
  githubUrl: string | null;
}

/** GET /api/verse/wiki/repo/<key>/page/<id> */
export interface WikiPageView {
  meta: Pick<WikiPageMeta, 'id' | 'title' | 'kind' | 'purpose' | 'parent' | 'commit' | 'generatedAt' | 'model' | 'citations' | 'droppedCitations'>;
  markdown: string;
}

/** The per-repo line index stored with the wiki: rel path -> line count. Used to verify citations without reading the repo. */
export type WikiFileIndex = Record<string, number>;

export interface WikiAskSource {
  repo: string;
  repoName: string;
  file: string;
  line: number;
  endLine?: number;
  /** Where the passage came from. */
  via: 'wiki' | 'index' | 'genome';
  /** Wiki page id when via === 'wiki'. */
  page?: string;
  title?: string;
}

export interface WikiAskResult {
  question: string;
  /** The repo the answer is about (the best-matching one when no repo was given). */
  repo: string | null;
  repoKey: string | null;
  repoName: string | null;
  /** Other repos with relevant matches (multi-repo asks only). */
  alsoIn: Array<{ repoKey: string; repoName: string }>;
  /** `answered` (model synthesis with verified citations), `extractive` (no model: best passages), `not-found`. */
  status: 'answered' | 'extractive' | 'not-found';
  answer: string;
  sources: WikiAskSource[];
  engine: string;
  /** True when no code left this machine for the answer. */
  local: boolean;
  droppedCitations: number;
}
