#!/usr/bin/env node
/**
 * scripts/build-sea.mjs — Bun single-executable build for the Tauri sidecar.
 *
 * What it does:
 *   1. Runs `npm run build` (tsc + copy-assets) to ensure dist/ is fresh.
 *   2. Writes a thin shim entry (dist-bin/_entry.js) that sets
 *      ASHLR_WEB_PUBLIC to the sibling `public/` dir before importing the CLI.
 *      This means the compiled binary self-configures the asset path at runtime
 *      without any external launcher wrapper needed.
 *   3. Compiles shim → dist-bin/ashlr  via `bun build --compile`.
 *   4. Copies dist/core/web/public/ → dist-bin/public/ so the binary and its
 *      assets are co-located.
 *
 * Usage:
 *   node scripts/build-sea.mjs
 *   # or: npm run build:binary
 *
 * Output:
 *   dist-bin/ashlr          — self-contained native binary (~10–15 MB)
 *   dist-bin/public/        — SPA assets (index.html, app.js, styles.css)
 *
 * The binary sets ASHLR_WEB_PUBLIC automatically — no env var needed when
 * launching directly.  When run via Tauri sidecar, the env is also injected
 * by main.rs as a belt-and-suspenders measure.
 *
 * Requirements: Bun >= 1.x on PATH (or at ASHLR_BUN_PATH).
 */

import { execSync, spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(join(here, '..'));
const distBin = join(repoRoot, 'dist-bin');
const distWeb = join(repoRoot, 'dist', 'core', 'web', 'public');
const entry   = join(distBin, '_entry.js');
const outBin  = join(distBin, 'ashlr');
const pubDest = join(distBin, 'public');

// ── locate bun ───────────────────────────────────────────────────────────────
const BUN = process.env.ASHLR_BUN_PATH ??
  (() => {
    // Try the standard Bun install location first, then PATH.
    const wellKnown = join(process.env.HOME ?? '', '.bun', 'bin', 'bun');
    if (existsSync(wellKnown)) return wellKnown;
    try {
      return execSync('which bun', { encoding: 'utf8' }).trim();
    } catch {
      return null;
    }
  })();

if (!BUN) {
  console.error(
    'ERROR: bun not found. Install via https://bun.sh or set ASHLR_BUN_PATH.',
  );
  process.exit(1);
}
console.log(`[build-sea] Using bun: ${BUN}`);

// ── 1. Ensure dist/ is fresh ─────────────────────────────────────────────────
console.log('[build-sea] Running npm run build (tsc + copy-assets)…');
execSync('npm run build', { cwd: repoRoot, stdio: 'inherit' });

if (!existsSync(distWeb)) {
  console.error(`ERROR: dist/core/web/public not found after build: ${distWeb}`);
  process.exit(1);
}

// ── 2. Write thin shim entry ─────────────────────────────────────────────────
// The shim sets ASHLR_WEB_PUBLIC and ASHLR_VERSION before the CLI boots:
//   ASHLR_WEB_PUBLIC — points to the sibling `public/` dir resolved via
//     import.meta.dir (the directory of the *binary* at runtime in Bun).
//   ASHLR_VERSION — baked in at build time because createRequire cannot reach
//     ../../package.json from inside Bun's virtual FS (/$bunfs/root/…).
//
// Both env vars are set only when not already set so an external caller
// (e.g. Tauri sidecar) can override them.
mkdirSync(distBin, { recursive: true });

const pkgVersion = JSON.parse(
  readFileSync(join(repoRoot, 'package.json'), 'utf8'),
).version ?? '0.0.0';

const shimSrc = `// Auto-generated by scripts/build-sea.mjs — do not edit manually.
// Sets ASHLR_WEB_PUBLIC and ASHLR_VERSION before the CLI boots so that:
//   - assetsDir() finds the SPA assets next to this compiled binary.
//   - --version works without reading ../../package.json from the virtual FS.
//
// NOTE: Inside a Bun-compiled binary, import.meta.dir resolves to the virtual
// FS path (/$bunfs/root/…), NOT the real filesystem location of the binary.
// process.execPath IS the real path to the binary — use dirname() on that.
import { dirname } from 'node:path';
if (!process.env.ASHLR_WEB_PUBLIC) {
  process.env.ASHLR_WEB_PUBLIC = dirname(process.execPath) + '/public';
}
if (!process.env.ASHLR_VERSION) {
  process.env.ASHLR_VERSION = ${JSON.stringify(pkgVersion)};
}
await import('../dist/cli/index.js');
`;

writeFileSync(entry, shimSrc, 'utf8');
console.log(`[build-sea] Wrote shim entry: ${entry}`);

// ── 3. bun build --compile ───────────────────────────────────────────────────
// Remove stale binary first so a partial build doesn't look successful.
if (existsSync(outBin)) rmSync(outBin);

console.log(`[build-sea] Compiling → ${outBin} …`);
const result = spawnSync(
  BUN,
  ['build', '--compile', entry, '--outfile', outBin],
  { cwd: repoRoot, stdio: 'inherit' },
);
if (result.status !== 0) {
  console.error('[build-sea] bun build --compile failed.');
  process.exit(result.status ?? 1);
}

// Confirm the binary exists and report size.
const { statSync } = await import('node:fs');
const binStat = statSync(outBin);
const sizeMB  = (binStat.size / 1_048_576).toFixed(1);
console.log(`[build-sea] Binary: ${outBin}  (${sizeMB} MB)`);

// ── 4. Copy SPA assets next to the binary ────────────────────────────────────
if (existsSync(pubDest)) rmSync(pubDest, { recursive: true });
cpSync(distWeb, pubDest, { recursive: true });
console.log(`[build-sea] Assets: ${distWeb} → ${pubDest}`);

console.log('\n[build-sea] Done.');
console.log(`  Binary : ${outBin}`);
console.log(`  Assets : ${pubDest}`);
console.log(`\nSmoke test:`);
console.log(`  ${outBin} --version`);
console.log(`  ASHLR_WEB_PUBLIC=${pubDest} ${outBin} serve &`);
console.log(`  curl -s http://127.0.0.1:7777 | head -5`);
