#!/usr/bin/env node
/**
 * scripts/build-sea.mjs — Bun single-executable build for the Tauri sidecar.
 *
 * What it does:
 *   1. Runs `npm run build`, or freshly verifies explicitly adopted CI bytes.
 *   2. Writes a thin shim entry (dist-bin/_entry.js) that sets
 *      ASHLR_WEB_PUBLIC to the sibling `public/` dir before importing the CLI.
 *      This means the compiled binary self-configures the asset path at runtime
 *      without any external launcher wrapper needed.
 *   3. Writes sibling worker shims (read projections, engineering, fleet
 *      history) with the same build identity, then compiles every entrypoint
 *      → dist-bin/ashlr via `bun build --compile`.
 *   4. Copies dist/core/web/public/ → dist-bin/public/ so the binary and its
 *      assets are co-located.
 *
 * Usage:
 *   node scripts/build-sea.mjs
 *   # or: npm run build:binary
 *   # Verified CI reuse: see docs/RELEASING.md#qualified-ci-build-handoff.
 *
 * Output:
 *   dist-bin/ashlr          — self-contained native binary (~10–15 MB)
 *   dist-bin/public/        — SPA assets (index.html, app.js, styles.css)
 *
 * The binary sets ASHLR_WEB_PUBLIC automatically — no env var needed when
 * launching directly.  When run via Tauri sidecar, the env is also injected
 * by main.rs as a belt-and-suspenders measure.
 *
 * Requirements: Bun >= 1.x on PATH (or at ASHLR_BUN_PATH).
 */

import { execSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createBuildIdentity, javascriptStringLiteral } from './build-identity.mjs';
import { validateAdoptedArtifact, verifyArtifact } from './hosted-build-artifact.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(join(here, '..'));
const distBin = join(repoRoot, 'dist-bin');
const distWeb = join(repoRoot, 'dist', 'core', 'web', 'public');
const entry   = join(distBin, '_entry.js');
const workerEntry = join(distBin, 'read-projection-worker.js');
const engineeringWorkerEntry = join(distBin, 'engineering-background-worker.js');
const engineeringReadWorkerEntry = join(distBin, 'engineering-successor-read-worker.js');
// V3.10: fleet-history.ts resolves `./fleet-history-worker.js` next to the main
// entry, like read-projections.ts does. Without this sibling the bundled
// binary cannot start the worker and runs the scorecard snapshot inline
// (~1.6 s blocking once a day).
const fleetHistoryWorkerEntry = join(distBin, 'fleet-history-worker.js');
const outcomesWorkerEntry = join(distBin, 'outcomes-worker.js');
const outBin  = join(distBin, process.platform === 'win32' ? 'ashlr.exe' : 'ashlr');
const pubDest = join(distBin, 'public');
const buildIdentityPath = join(repoRoot, 'dist', 'build-identity.json');

/**
 * V3.10 (review finding c13): the operand-free flag on which the compiled
 * binary re-enters itself to run the scorecard-history custody helper. MUST
 * equal SCORECARD_HISTORY_HELPER_FLAG in src/core/fleet/scorecard-history.ts
 * (test/scorecard-history-sea-310.test.ts pins them together).
 */
export const SCORECARD_HISTORY_HELPER_FLAG = '--_scorecard-history-helper';

// Closed source inventory for the native read-only structural diagnostic.
// Pinned against the runtime reader by the build/safety tests.
export const VERIFY_SAFETY_SOURCE_KEYS = Object.freeze([
  'sandbox/policy', 'daemon/loop', 'knowledge/index', 'knowledge/graph', 'run/provider-client',
]);

export function collectVerifySafetySources({ coreRoot, buildIdentityJson }) {
  const sources = {};
  for (const key of VERIFY_SAFETY_SOURCE_KEYS) {
    const text = readFileSync(join(coreRoot, `${key}.js`), 'utf8');
    if (!text) throw new Error(`Empty native safety source: ${key}`);
    sources[key] = { text, sha256: createHash('sha256').update(text, 'utf8').digest('hex') };
  }
  return JSON.stringify({ schemaVersion: 1, buildIdentityJson, sources });
}

/** Exact source-owned tool worker snapshot; never an account/authority proof. */
export function collectClaudeToolWorkerSource({ coreRoot, buildIdentityJson }) {
  const text = readFileSync(join(coreRoot, 'sandbox/claude-broker-tool-worker.js'), 'utf8');
  if (!text || Buffer.byteLength(text) > 128 * 1024) throw new Error('Invalid native Claude tool worker source');
  return JSON.stringify({ schemaVersion: 1, buildIdentityJson, text,
    sha256: createHash('sha256').update(text, 'utf8').digest('hex') });
}

export function createSeaShim({ pkgVersion, buildIdentityJson, verifySafetySourcesJson, claudeToolWorkerSourceJson, desktopPairIdentityJson }) {
  return `// Auto-generated by scripts/build-sea.mjs — do not edit manually.
// Sets ASHLR_WEB_PUBLIC and ASHLR_VERSION before the CLI boots so that:
//   - assetsDir() finds the SPA assets next to this compiled binary.
//   - --version works without reading ../../package.json from the virtual FS.
//
// NOTE: Inside a Bun-compiled binary, import.meta.dir resolves to the virtual
// FS path (/$bunfs/root/…), NOT the real filesystem location of the binary.
// process.execPath IS the real path to the binary — use dirname() on that.
import { dirname } from 'node:path';
// Scorecard history's one-shot custody helper is a CHILD PROCESS (its cwd is
// the pinned history directory — a Worker thread cannot chdir), and inside
// this binary it has no on-disk script to spawn. scorecard-history.ts
// therefore re-executes this binary with exactly one fixed, operand-free
// flag, dispatched here to the same helper script compiled in. The flag must
// be the ENTIRE argv; it carries no path or module specifier, and the helper
// validates its stdin request (pinned root identity) before any file access.
if (process.argv.length === 3 && process.argv[2] === ${JSON.stringify(SCORECARD_HISTORY_HELPER_FLAG)}) {
  await import('../scripts/scorecard-history-worker.mjs');
} else {
if (!process.env.ASHLR_WEB_PUBLIC) {
  process.env.ASHLR_WEB_PUBLIC = dirname(process.execPath) + '/public';
}
if (!process.env.ASHLR_VERSION) {
  process.env.ASHLR_VERSION = ${JSON.stringify(pkgVersion)};
}
Reflect.set(
  globalThis,
  Symbol.for('ashlr.build-identity.v1'),
  ${javascriptStringLiteral(buildIdentityJson)},
);
${desktopPairIdentityJson === undefined ? '' : `Reflect.set(globalThis, Symbol.for('phantom.desktop-pair-build.v1'), ${javascriptStringLiteral(desktopPairIdentityJson)});`}
${verifySafetySourcesJson === undefined ? '' : `Reflect.set(globalThis, Symbol.for('ashlr.verify-safety-sources.v1'), ${javascriptStringLiteral(verifySafetySourcesJson)});`}
${claudeToolWorkerSourceJson === undefined ? '' : `Reflect.set(globalThis, Symbol.for('ashlr.claude-tool-worker-source.v1'), ${javascriptStringLiteral(claudeToolWorkerSourceJson)});`}
await import('../dist/cli/index.js');
}
`;
}

export function createSeaWorkerShim({ buildIdentityJson }) {
  return `// Auto-generated sibling entry for the compiled read-projection worker.
// Worker globals are separate, so embed the same trusted artifact identity.
Reflect.set(
  globalThis,
  Symbol.for('ashlr.build-identity.v1'),
  ${javascriptStringLiteral(buildIdentityJson)},
);
await import('../dist/core/web/read-projection-worker.js');
`;
}

export function createSeaEngineeringWorkerShim({ buildIdentityJson }) {
  return `// Fixed effectful engineering worker; never an arbitrary entrypoint.
Reflect.set(globalThis, Symbol.for('ashlr.build-identity.v1'), ${javascriptStringLiteral(buildIdentityJson)});
await import('../dist/core/resources/engineering-background-worker.js');
`;
}

export function createSeaEngineeringReadWorkerShim({ buildIdentityJson }) {
  return `// Fixed read-only successor journal worker.
Reflect.set(globalThis, Symbol.for('ashlr.build-identity.v1'), ${javascriptStringLiteral(buildIdentityJson)});
await import('../dist/core/resources/engineering-successor-read-worker.js');
`;
}

export function createSeaFleetHistoryWorkerShim({ buildIdentityJson }) {
  return `// Fixed read-mostly fleet-history worker (scorecard snapshot + trends).
// Worker globals are separate, so embed the same trusted artifact identity.
Reflect.set(globalThis, Symbol.for('ashlr.build-identity.v1'), ${javascriptStringLiteral(buildIdentityJson)});
await import('../dist/core/verse/fleet-history-worker.js');
`;
}

export function createSeaOutcomesWorkerShim({ buildIdentityJson }) {
  return `// Fixed outcome metadata worker; never an arbitrary planner/provider entry.
Reflect.set(globalThis, Symbol.for('ashlr.build-identity.v1'), ${javascriptStringLiteral(buildIdentityJson)});
await import('../dist/core/verse/outcomes-worker.js');
`;
}

/**
 * @param {{ entry: string, workerEntry: string, engineeringWorkerEntry?: string,
 *   engineeringReadWorkerEntry?: string, fleetHistoryWorkerEntry?: string, outcomesWorkerEntry?: string, outBin: string }} args
 */
export function createSeaCompileArgs({
  entry, workerEntry, engineeringWorkerEntry, engineeringReadWorkerEntry, fleetHistoryWorkerEntry, outcomesWorkerEntry, outBin,
}) {
  // Bun does not discover Worker URLs automatically. All shims must be
  // siblings: bundled import.meta.url resolves relative to the main entry.
  return ['build', '--compile', entry, workerEntry, ...(engineeringWorkerEntry ? [engineeringWorkerEntry] : []),
    ...(engineeringReadWorkerEntry ? [engineeringReadWorkerEntry] : []),
    ...(fleetHistoryWorkerEntry ? [fleetHistoryWorkerEntry] : []), ...(outcomesWorkerEntry ? [outcomesWorkerEntry] : []), '--outfile', outBin];
}

export function parseHostedBuildArguments(args) {
  if (args.length === 0) return null;
  const allowed = ['--hosted-bundle', '--run', '--attempt', '--attestor-sha', '--attestor-run', '--attestor-attempt'];
  const flags = {};
  for (let i = 0; i < args.length; i += 2) {
    if (!allowed.includes(args[i]) || typeof args[i + 1] !== 'string' || !args[i + 1] || Object.hasOwn(flags, args[i])) throw new Error('Invalid hosted build arguments');
    flags[args[i]] = args[i + 1];
  }
  if (allowed.some((key) => !Object.hasOwn(flags, key)) || !isAbsolute(flags['--hosted-bundle']) || !/^[a-f0-9]{40}$/.test(flags['--attestor-sha'])) throw new Error('Complete hosted build identity required');
  for (const key of ['--run', '--attempt', '--attestor-run', '--attestor-attempt']) {
    if (!/^[1-9][0-9]*$/.test(flags[key]) || !Number.isSafeInteger(Number(flags[key]))) throw new Error('Invalid hosted run identity');
  }
  return { bundle: flags['--hosted-bundle'], runId: Number(flags['--run']), runAttempt: Number(flags['--attempt']),
    attestorSha: flags['--attestor-sha'], attestorRun: Number(flags['--attestor-run']), attestorAttempt: Number(flags['--attestor-attempt']) };
}

export function ensureSeaBuild({ args, root, build = () => execSync('npm run build', { cwd: root, stdio: 'inherit' }),
  identity = createBuildIdentity, verify = verifyArtifact, validate = validateAdoptedArtifact }) {
  const hosted = parseHostedBuildArguments(args);
  if (!hosted) { build(); return { mode: 'local' }; }
  const current = identity({ repoRoot: root });
  if (current.provenance !== 'git' || current.dirty !== false || !current.revision) throw new Error('Clean source identity required for hosted native build');
  const { bundle, ...policy } = hosted;
  const receipt = verify({ root, revision: current.revision, bundle, policy });
  validate(receipt);
  return { mode: 'hosted', receipt };
}

async function main() {
parseHostedBuildArguments(process.argv.slice(2));

// ── locate bun ───────────────────────────────────────────────────────────────
const BUN = process.env.ASHLR_BUN_PATH ??
  (() => {
    // Try the standard Bun install location first, then PATH.
    const isWin = process.platform === 'win32';
    const home = process.env.HOME ?? process.env.USERPROFILE ?? '';
    const wellKnown = join(home, '.bun', 'bin', isWin ? 'bun.exe' : 'bun');
    if (existsSync(wellKnown)) return wellKnown;
    try {
      const out = execSync(isWin ? 'where bun' : 'which bun', { encoding: 'utf8' });
      return out.split(/\r?\n/).map((s) => s.trim()).find(Boolean) ?? (isWin ? 'bun.exe' : null);
    } catch {
      return isWin ? 'bun.exe' : null;
    }
  })();

if (!BUN) {
  console.error(
    'ERROR: bun not found. Install via https://bun.sh or set ASHLR_BUN_PATH.',
  );
  process.exit(1);
}
console.log(`[build-sea] Using bun: ${BUN}`);

// ── 1. Ensure dist/ is fresh ─────────────────────────────────────────────────
console.log('[build-sea] Preparing source-bound JavaScript build…');
const prepared = ensureSeaBuild({ args: process.argv.slice(2), root: repoRoot });
console.log(`[build-sea] ${prepared.mode === 'hosted' ? 'Verified adopted CI bytes; native compilation follows' : 'Local npm build complete'}`);

if (!existsSync(distWeb)) {
  console.error(`ERROR: dist/core/web/public not found after build: ${distWeb}`);
  process.exit(1);
}

// ── 2. Write thin shim entry ─────────────────────────────────────────────────
// The shim sets ASHLR_WEB_PUBLIC and ASHLR_VERSION before the CLI boots:
//   ASHLR_WEB_PUBLIC — points to the sibling `public/` dir resolved via
//     import.meta.dir (the directory of the *binary* at runtime in Bun).
//   ASHLR_VERSION — baked in at build time because createRequire cannot reach
//     ../../package.json from inside Bun's virtual FS (/$bunfs/root/…).
//
// Runtime configuration remains caller-overridable, but canonical build
// identity is always the value embedded into this artifact.
mkdirSync(distBin, { recursive: true });

const pkgVersion = JSON.parse(
  readFileSync(join(repoRoot, 'package.json'), 'utf8'),
).version ?? '0.0.0';
const buildIdentityJson = readFileSync(buildIdentityPath, 'utf8').trim();

const verifySafetySourcesJson = collectVerifySafetySources({
  coreRoot: join(repoRoot, 'dist', 'core'), buildIdentityJson,
});
const claudeToolWorkerSourceJson = collectClaudeToolWorkerSource({
  coreRoot: join(repoRoot, 'dist', 'core'), buildIdentityJson,
});
const source = prepared.mode === 'hosted' ? prepared.receipt.source : null;
const desktopPairIdentityJson = source ? JSON.stringify({ schemaVersion: 1, revision: source.revision, tree: source.tree, version: pkgVersion }) : undefined;
const shimSrc = createSeaShim({ pkgVersion, buildIdentityJson, verifySafetySourcesJson, claudeToolWorkerSourceJson, desktopPairIdentityJson });

writeFileSync(entry, shimSrc, 'utf8');
writeFileSync(workerEntry, createSeaWorkerShim({ buildIdentityJson }), 'utf8');
writeFileSync(outcomesWorkerEntry, createSeaOutcomesWorkerShim({ buildIdentityJson }), 'utf8');
writeFileSync(engineeringWorkerEntry, createSeaEngineeringWorkerShim({ buildIdentityJson }), 'utf8');
writeFileSync(engineeringReadWorkerEntry, createSeaEngineeringReadWorkerShim({ buildIdentityJson }), 'utf8');
writeFileSync(fleetHistoryWorkerEntry, createSeaFleetHistoryWorkerShim({ buildIdentityJson }), 'utf8');
console.log(`[build-sea] Wrote shim entry: ${entry}`);

// ── 3. bun build --compile ───────────────────────────────────────────────────
// Remove stale binary first so a partial build doesn't look successful.
if (existsSync(outBin)) rmSync(outBin);

console.log(`[build-sea] Compiling → ${outBin} …`);
const result = spawnSync(
  BUN,
  createSeaCompileArgs({ entry, workerEntry, engineeringWorkerEntry, engineeringReadWorkerEntry, fleetHistoryWorkerEntry, outcomesWorkerEntry, outBin }),
  { cwd: repoRoot, encoding: 'utf8' },
);
if (result.stdout) process.stdout.write(result.stdout);
if (result.status !== 0) {
  console.error(`[build-sea] bun build --compile failed (exit ${result.status}).`);
  if (result.stderr) console.error('[build-sea] bun stderr:\n' + result.stderr);
  if (result.error) console.error('[build-sea] spawn error:', result.error);
  process.exit(result.status ?? 1);
}

// Confirm the binary exists and report size.
const { statSync } = await import('node:fs');
const binStat = statSync(outBin);
const sizeMB  = (binStat.size / 1_048_576).toFixed(1);
console.log(`[build-sea] Binary: ${outBin}  (${sizeMB} MB)`);

// ── 4. Copy SPA assets next to the binary ────────────────────────────────────
if (existsSync(pubDest)) rmSync(pubDest, { recursive: true });
cpSync(distWeb, pubDest, { recursive: true });
console.log(`[build-sea] Assets: ${distWeb} → ${pubDest}`);

console.log('\n[build-sea] Done.');
console.log(`  Binary : ${outBin}`);
console.log(`  Assets : ${pubDest}`);
console.log(`\nSmoke test:`);
console.log(`  ${outBin} --version`);
console.log(`  ASHLR_WEB_PUBLIC=${pubDest} ${outBin} serve &`);
console.log(`  curl -s http://127.0.0.1:7777 | head -5`);
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : '';
if (import.meta.url === invokedPath) {
  await main();
}
