/**
 * core/verse/shell-integration.ts — command blocks for the Terminal (3.15).
 *
 * WHAT. A terminal tab's shell learns to MARK its own output: where the
 * prompt starts (OSC 133;A), where the typed command starts (133;B), where
 * it began executing (133;C), and where it finished with which exit status
 * (133;D;<n>). It also reports the command line as typed (OSC 633;E, the
 * VS Code convention) and its working directory (OSC 633;P;Cwd=…). The
 * Terminal manager cuts the byte stream at those marks into BLOCKS
 * (terminal-blocks.ts): one command, its duration, its exit code, its output.
 *
 * HOW, WITHOUT TOUCHING YOUR DOTFILES. Nothing is written to ~/.zshrc and
 * friends, and nothing is ever appended to a file the operator owns. Instead
 * each supported shell is STARTED so it reads a small script of ours, which
 * first loads the operator's own startup files exactly as the shell would
 * have, then installs the hooks:
 *
 *   zsh  — `ZDOTDIR` points at our directory. Its .zshenv/.zprofile/.zshrc/
 *          .zlogin source YOUR files from your real ZDOTDIR (or $HOME), with
 *          ZDOTDIR set back to yours while they run, then restore ZDOTDIR
 *          (or unset it) for good once startup is over. Argv is unchanged
 *          (`zsh -l`).
 *   bash — `bash --init-file <ours>` (an interactive shell reads it INSTEAD
 *          of ~/.bashrc). It sources /etc/profile and the first of
 *          ~/.bash_profile, ~/.bash_login, ~/.profile — what `bash -l`
 *          reads — then hooks PROMPT_COMMAND and a DEBUG trap (or
 *          bash-preexec's arrays when that is installed; never over a DEBUG
 *          trap someone else owns).
 *   fish — `fish -l --init-command 'source <ours>'`: fish reads its config
 *          as usual, then ours adds event handlers.
 *   anything else (sh, ksh, dash, nu…) — started exactly as before, no blocks.
 *
 * The scripts live in a per-user directory under the OS temp dir (macOS'
 * $TMPDIR is already private to the user), created 0700, refused if it is a
 * symlink or not ours — a shared /tmp on Linux must not let another user
 * plant code our shells would source. They are regenerated (atomically) if
 * missing, since the OS may clean temp files.
 *
 * FORGERY. Any program can print OSC 133 — `cat` a file that contains one
 * and a fake block boundary appears. That only mis-draws a block. The
 * command LINE is different (it is what "Explain this error" sends to a
 * chat), so 633;E carries a per-tab nonce the shell reads from
 * ASHLR_SHELL_NONCE and immediately unsets; an E without it is ignored.
 */
import { randomBytes } from 'node:crypto';
import { lstat, mkdir, rename, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, isAbsolute, join } from 'node:path';

/** Bump when a script changes: a new directory, so a running shell's files are never edited under it. */
export const SHELL_INTEGRATION_VERSION = 1;

export type IntegratedShell = 'zsh' | 'bash' | 'fish';

export function integratedShellKind(shellPath: string): IntegratedShell | null {
  const name = basename(shellPath);
  if (name === 'zsh' || name === 'bash' || name === 'fish') return name;
  return null;
}

// ---------------------------------------------------------------------------
// The scripts
// ---------------------------------------------------------------------------

const HEADER = (shell: string) => `# Ashlr Verse — shell integration for ${shell} (v${SHELL_INTEGRATION_VERSION}).
# Generated by Ashlr; safe to delete (it is recreated when needed).
# It loads YOUR startup files unchanged, then marks prompts and commands with
# OSC 133 / OSC 633 so the Verse terminal can show each command as a block.
# Nothing here writes to your dotfiles.
`;

/** zsh: the four startup files of our ZDOTDIR, plus the hook script they end with. */
export function zshIntegrationFiles(): Record<string, string> {
  const sourceUser = (file: string) => `if [[ -f "$__ashlr_user_zdotdir/${file}" ]]; then
  ZDOTDIR="$__ashlr_user_zdotdir"
  builtin source "$__ashlr_user_zdotdir/${file}"
  if [[ "$ZDOTDIR" != "$__ashlr_user_zdotdir" ]]; then
    __ashlr_user_zdotdir="$ZDOTDIR"
    __ashlr_user_zdotdir_set=1
  fi
  ZDOTDIR="$__ashlr_si_dir"
fi
`;
  return {
    '.zshenv': `${HEADER('zsh')}
typeset -g __ashlr_si_dir="$ZDOTDIR"
if [[ -n "\${ASHLR_USER_ZDOTDIR+x}" ]]; then
  typeset -g __ashlr_user_zdotdir="$ASHLR_USER_ZDOTDIR"
  typeset -gi __ashlr_user_zdotdir_set=1
else
  typeset -g __ashlr_user_zdotdir="$HOME"
  typeset -gi __ashlr_user_zdotdir_set=0
fi
builtin unset ASHLR_USER_ZDOTDIR
__ashlr_restore_zdotdir() {
  if (( __ashlr_user_zdotdir_set )); then
    builtin export ZDOTDIR="$__ashlr_user_zdotdir"
  else
    builtin unset ZDOTDIR
  fi
  builtin unset -f __ashlr_restore_zdotdir
}
${sourceUser('.zshenv')}`,
    '.zprofile': `${HEADER('zsh')}
${sourceUser('.zprofile')}`,
    '.zshrc': `${HEADER('zsh')}
${sourceUser('.zshrc')}
builtin source "$__ashlr_si_dir/ashlr-integration.zsh"
# A non-login shell reads no .zlogin: give ZDOTDIR back now.
if [[ ! -o login ]] && (( $+functions[__ashlr_restore_zdotdir] )); then __ashlr_restore_zdotdir; fi
`,
    '.zlogin': `${HEADER('zsh')}
${sourceUser('.zlogin')}
if (( $+functions[__ashlr_restore_zdotdir] )); then __ashlr_restore_zdotdir; fi
`,
    'ashlr-integration.zsh': `${HEADER('zsh')}
if [[ -n "\${__ashlr_si_loaded-}" || ! -o interactive ]]; then builtin return 0; fi
typeset -g __ashlr_si_loaded=1
typeset -g __ashlr_nonce="\${ASHLR_SHELL_NONCE-}"
builtin unset ASHLR_SHELL_NONCE
typeset -gi __ashlr_in_command=0
typeset -gi __ashlr_status=0

# OSC 633 escaping: backslash, ';' and control characters as \\xNN.
__ashlr_esc() {
  builtin local s="$1"
  s="\${s//\\\\/\\\\\\\\}"
  s="\${s//;/\\\\x3b}"
  s="\${s//$'\\n'/\\\\x0a}"
  s="\${s//$'\\r'/\\\\x0d}"
  s="\${s//$'\\e'/\\\\x1b}"
  s="\${s//$'\\a'/\\\\x07}"
  REPLY="$s"
}

# Runs FIRST among the precmd hooks, so $? is still the command's status.
__ashlr_status_hook() { __ashlr_status=$? }

# Runs LAST, after any prompt theme has rebuilt PS1.
__ashlr_precmd() {
  if (( __ashlr_in_command )); then
    builtin printf '\\033]133;D;%s\\007' "$__ashlr_status"
    __ashlr_in_command=0
  fi
  __ashlr_esc "$PWD"
  builtin printf '\\033]633;P;Cwd=%s\\007' "$REPLY"
  if [[ "$PS1" != *$'\\e]133;B\\a'* ]]; then
    PS1=$'%{\\e]133;A\\a%}'"$PS1"$'%{\\e]133;B\\a%}'
  fi
}

__ashlr_preexec() {
  __ashlr_esc "$1"
  builtin printf '\\033]633;E;%s;%s\\007' "$REPLY" "$__ashlr_nonce"
  builtin printf '\\033]133;C\\007'
  __ashlr_in_command=1
}

precmd_functions=(__ashlr_status_hook \${precmd_functions[@]} __ashlr_precmd)
preexec_functions+=(__ashlr_preexec)
`,
  };
}

/** bash: one --init-file that stands in for a login shell's startup, then hooks. */
export function bashIntegrationScript(): string {
  return `${HEADER('bash')}
if [ -n "\${__ashlr_si_loaded-}" ]; then return 0 2>/dev/null; fi
__ashlr_si_loaded=1

# What \`bash -l\` reads (--init-file replaces it).
if [ -r /etc/profile ]; then . /etc/profile; fi
if [ -r "$HOME/.bash_profile" ]; then . "$HOME/.bash_profile"
elif [ -r "$HOME/.bash_login" ]; then . "$HOME/.bash_login"
elif [ -r "$HOME/.profile" ]; then . "$HOME/.profile"
fi

case $- in *i*) ;; *) return 0 2>/dev/null ;; esac

__ashlr_nonce="\${ASHLR_SHELL_NONCE-}"
unset ASHLR_SHELL_NONCE
__ashlr_in_command=0
__ashlr_at_prompt=0
__ashlr_status=0
__ashlr_last_hist=

__ashlr_esc() {
  local s="$1"
  s="\${s//\\\\/\\\\\\\\}"
  s="\${s//;/\\\\x3b}"
  s="\${s//$'\\n'/\\\\x0a}"
  s="\${s//$'\\r'/\\\\x0d}"
  s="\${s//$'\\e'/\\\\x1b}"
  s="\${s//$'\\a'/\\\\x07}"
  __ashlr_reply="$s"
}

__ashlr_precmd() {
  if [ "$__ashlr_in_command" = 1 ]; then
    builtin printf '\\033]133;D;%s\\007' "$__ashlr_status"
    __ashlr_in_command=0
  fi
  __ashlr_esc "$PWD"
  builtin printf '\\033]633;P;Cwd=%s\\007' "$__ashlr_reply"
  case "$PS1" in
    *'133;B'*) ;;
    *) PS1='\\[\\033]133;A\\007\\]'"$PS1"'\\[\\033]133;B\\007\\]' ;;
  esac
  __ashlr_at_prompt=1
}

__ashlr_command_started() {
  __ashlr_esc "$1"
  builtin printf '\\033]633;E;%s;%s\\007' "$__ashlr_reply" "$__ashlr_nonce"
  builtin printf '\\033]133;C\\007'
  __ashlr_in_command=1
}

# DEBUG trap: the first simple command after a prompt is the command line.
__ashlr_preexec() {
  [ "$__ashlr_at_prompt" = 1 ] || return 0
  __ashlr_at_prompt=0
  local line num cmd="$BASH_COMMAND"
  line="$(HISTTIMEFORMAT= builtin history 1 2>/dev/null)"
  if [[ $line =~ ^[[:space:]]*([0-9]+)[*]?[[:space:]]+(.*)$ ]]; then
    num="\${BASH_REMATCH[1]}"
    if [ "$num" != "$__ashlr_last_hist" ]; then cmd="\${BASH_REMATCH[2]}"; __ashlr_last_hist="$num"; fi
  fi
  __ashlr_command_started "$cmd"
}

__ashlr_precmd_bp() { __ashlr_status=$?; __ashlr_precmd; }
__ashlr_preexec_bp() { __ashlr_command_started "$1"; }

if [ -n "\${bash_preexec_imported-}\${__bp_imported-}" ]; then
  # bash-preexec owns the DEBUG trap and PROMPT_COMMAND: join its arrays.
  precmd_functions+=(__ashlr_precmd_bp)
  preexec_functions+=(__ashlr_preexec_bp)
else
  if declare -p PROMPT_COMMAND 2>/dev/null | grep -q '^declare -a'; then
    PROMPT_COMMAND=('__ashlr_status=$?' "\${PROMPT_COMMAND[@]}" '__ashlr_precmd')
  else
    __ashlr_user_pc="\${PROMPT_COMMAND-}"
    while [[ "$__ashlr_user_pc" =~ ^(.*)[[:space:]\\;]$ ]]; do __ashlr_user_pc="\${BASH_REMATCH[1]}"; done
    PROMPT_COMMAND='__ashlr_status=$?; '"\${__ashlr_user_pc:+$__ashlr_user_pc; }"'__ashlr_precmd'
    unset __ashlr_user_pc
  fi
  # Someone else's DEBUG trap is left alone: prompts are still marked, commands are not.
  if [ -z "$(trap -p DEBUG)" ]; then trap '__ashlr_preexec' DEBUG; fi
fi
`;
}

/** fish: event handlers, loaded after the operator's config by --init-command. */
export function fishIntegrationScript(): string {
  return `${HEADER('fish')}
if set -q __ashlr_si_loaded; or not status is-interactive
  exit 0
end
set -g __ashlr_si_loaded 1
set -g __ashlr_nonce "$ASHLR_SHELL_NONCE"
set -e ASHLR_SHELL_NONCE
set -g __ashlr_in_command 0

function __ashlr_esc
  string join \\n -- $argv | string replace -a '\\\\' '\\\\\\\\' | string replace -a ';' '\\\\x3b' | string replace -a \\e '\\\\x1b' | string replace -a \\a '\\\\x07' | string replace -a \\r '\\\\x0d' | string join '\\\\x0a'
end

function __ashlr_preexec --on-event fish_preexec
  printf '\\033]633;E;%s;%s\\007' (__ashlr_esc $argv) $__ashlr_nonce
  printf '\\033]133;C\\007'
  set -g __ashlr_in_command 1
end

function __ashlr_postexec --on-event fish_postexec
  set -l s $status
  if test "$__ashlr_in_command" = 1
    printf '\\033]133;D;%s\\007' $s
    set -g __ashlr_in_command 0
  end
end

function __ashlr_prompt_start --on-event fish_prompt
  printf '\\033]633;P;Cwd=%s\\007' (__ashlr_esc $PWD)
  printf '\\033]133;A\\007'
end

if functions -q fish_prompt
  functions -c fish_prompt __ashlr_user_fish_prompt
  function fish_prompt
    __ashlr_user_fish_prompt
    printf '\\033]133;B\\007'
  end
end
`;
}

// ---------------------------------------------------------------------------
// Installing the scripts
// ---------------------------------------------------------------------------

/** The per-user directory the scripts are written to (never the operator's home). */
export function defaultShellIntegrationDir(): string {
  const uid = typeof process.getuid === 'function' ? process.getuid() : 'user';
  return join(tmpdir(), `ashlr-verse-shell-${uid}`, `v${SHELL_INTEGRATION_VERSION}`);
}

/** Refuse a directory we did not make: a symlink, someone else's, or writable by others. */
async function assertPrivateDir(dir: string): Promise<void> {
  const st = await lstat(dir);
  if (!st.isDirectory() || st.isSymbolicLink()) throw new Error('shell integration dir is not a plain directory');
  if (typeof process.getuid === 'function' && st.uid !== process.getuid()) throw new Error('shell integration dir is not ours');
  if (process.platform !== 'win32' && (st.mode & 0o022) !== 0) throw new Error('shell integration dir is writable by others');
}

async function writeAtomic(path: string, content: string): Promise<void> {
  const temp = `${path}.${randomBytes(4).toString('hex')}.tmp`;
  await writeFile(temp, content, { mode: 0o600 });
  await rename(temp, path);
}

async function fileHas(path: string, content: string): Promise<boolean> {
  try {
    const st = await lstat(path);
    // Same length is enough to skip a rewrite: the directory is versioned and private.
    return st.isFile() && !st.isSymbolicLink() && st.size === Buffer.byteLength(content);
  } catch {
    return false;
  }
}

/** Every file a shell kind needs, keyed by path relative to the integration dir. */
export function integrationFiles(kind: IntegratedShell): Record<string, string> {
  if (kind === 'zsh') {
    return Object.fromEntries(Object.entries(zshIntegrationFiles()).map(([name, body]) => [join('zsh', name), body]));
  }
  if (kind === 'bash') return { 'ashlr-integration.bash': bashIntegrationScript() };
  return { 'ashlr-integration.fish': fishIntegrationScript() };
}

/**
 * Write `kind`'s files under `dir` if they are missing. Async throughout —
 * this runs on a terminal-create request. Throws when the directory is not
 * safe to source from; the caller then starts the shell without integration.
 */
export async function ensureIntegrationFiles(dir: string, kind: IntegratedShell): Promise<void> {
  await mkdir(dir, { recursive: true, mode: 0o700 });
  // The parent too: it is the per-user directory another user could pre-create.
  await assertPrivateDir(join(dir, '..'));
  await assertPrivateDir(dir);
  const files = integrationFiles(kind);
  for (const [rel, body] of Object.entries(files)) {
    const path = join(dir, rel);
    const sub = join(path, '..');
    if (sub !== dir) {
      await mkdir(sub, { recursive: true, mode: 0o700 });
      await assertPrivateDir(sub);
    }
    if (!(await fileHas(path, body))) await writeAtomic(path, body);
  }
}

export interface IntegratedLaunch {
  argv: string[];
  /** Variables to ADD to the shell's environment. */
  env: Record<string, string>;
  kind: IntegratedShell;
}

/** Single-quote for fish (`\\` and `'` are the only escapes inside '…'). */
function fishQuote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/**
 * How to start `shell` with integration: argv and the variables to add.
 * `userEnv` is the environment the shell would otherwise get (for zsh's own
 * ZDOTDIR). Null when the shell is not one we integrate with.
 */
export function integratedLaunch(shell: string, dir: string, nonce: string, userEnv: Record<string, string>): IntegratedLaunch | null {
  const kind = integratedShellKind(shell);
  if (!kind) return null;
  const env: Record<string, string> = { ASHLR_SHELL_NONCE: nonce };
  if (kind === 'zsh') {
    const userZdotdir = userEnv['ZDOTDIR'];
    if (typeof userZdotdir === 'string' && userZdotdir.length > 0) env['ASHLR_USER_ZDOTDIR'] = userZdotdir;
    env['ZDOTDIR'] = join(dir, 'zsh');
    return { argv: [shell, '-l'], env, kind };
  }
  if (kind === 'bash') {
    return { argv: [shell, '--init-file', join(dir, 'ashlr-integration.bash')], env, kind };
  }
  return { argv: [shell, '-l', '--init-command', `source ${fishQuote(join(dir, 'ashlr-integration.fish'))}`], env, kind };
}

/** A fresh per-tab nonce (hex; never contains ';' or control characters). */
export function newShellNonce(): string {
  return randomBytes(12).toString('hex');
}

// ---------------------------------------------------------------------------
// Parsing the marks
// ---------------------------------------------------------------------------

export type ShellMark =
  | { kind: 'prompt-start' }
  | { kind: 'command-start' }
  | { kind: 'command-executed' }
  | { kind: 'command-finished'; exitCode: number | null }
  | { kind: 'command-line'; command: string; trusted: boolean }
  | { kind: 'cwd'; cwd: string };

/**
 * A mark and where its escape sequence sits in the chunk it was completed in:
 * `start` is the index of its ESC (NEGATIVE when the sequence began in an
 * earlier chunk — that many bytes of it were in the previous chunks), `end`
 * the index just past its terminator.
 */
export interface LocatedShellMark {
  mark: ShellMark;
  start: number;
  end: number;
}

const ESC = 0x1b;
const BEL = 0x07;
/** An OSC longer than this is not one of ours (a 633;E of a pasted script is the longest we expect). */
export const SHELL_MARK_MAX_BYTES = 32 * 1024;
export const SHELL_COMMAND_MAX_CHARS = 4_096;

/** Undo the scripts' escaping: `\\` → `\`, `\xNN` → the byte. */
export function unescapeOsc633(value: string): string {
  return value.replace(/\\(\\|x([0-9a-fA-F]{2}))/g, (_m, all: string, hex: string | undefined) =>
    hex ? String.fromCharCode(Number.parseInt(hex, 16)) : all,
  );
}

/** A command line fit to show and store: no control or bidi-override characters, capped. */
export function sanitizeCommandLine(raw: string): string {
  // Newlines inside a multi-line command survive as newlines; everything else goes.
  // eslint-disable-next-line no-control-regex
  const cleaned = raw.replace(/\r\n?/g, '\n').replace(/[\u0000-\u0009\u000b-\u001f\u007f-\u009f‎‏‪-‮⁦-⁩]/g, '').trim();
  return cleaned.length > SHELL_COMMAND_MAX_CHARS ? `${cleaned.slice(0, SHELL_COMMAND_MAX_CHARS - 1)}…` : cleaned;
}

function sanitizeCwd(raw: string): string | null {
  // eslint-disable-next-line no-control-regex
  if (raw.length === 0 || raw.length > 4096 || /[\u0000-\u001f\u007f]/.test(raw)) return null;
  return isAbsolute(raw) ? raw : null;
}

/** Interpret one OSC payload (between `ESC ]` and the terminator); null if it is not a mark. */
export function interpretOscPayload(payload: string, nonce: string | null): ShellMark | null {
  if (payload.startsWith('133;')) {
    const [, code = '', arg] = payload.split(';');
    switch (code) {
      case 'A': return { kind: 'prompt-start' };
      case 'B': return { kind: 'command-start' };
      case 'C': return { kind: 'command-executed' };
      case 'D': {
        const n = arg !== undefined && /^-?\d{1,4}$/.test(arg) ? Number(arg) : null;
        return { kind: 'command-finished', exitCode: n };
      }
      default: return null;
    }
  }
  if (payload.startsWith('633;E;')) {
    const rest = payload.slice(6);
    const cut = rest.lastIndexOf(';');
    const escaped = cut >= 0 ? rest.slice(0, cut) : rest;
    const given = cut >= 0 ? rest.slice(cut + 1) : '';
    const trusted = nonce !== null && nonce.length > 0 && given === nonce;
    return { kind: 'command-line', command: sanitizeCommandLine(unescapeOsc633(escaped)), trusted };
  }
  if (payload.startsWith('633;P;Cwd=')) {
    const cwd = sanitizeCwd(unescapeOsc633(payload.slice(10)));
    return cwd ? { kind: 'cwd', cwd } : null;
  }
  if (payload.startsWith('7;')) {
    // OSC 7: file://host/percent-encoded/path
    const m = /^7;file:\/\/[^/]*(\/.*)$/.exec(payload);
    if (!m) return null;
    let path: string;
    try {
      path = decodeURIComponent(m[1]!);
    } catch {
      return null;
    }
    const cwd = sanitizeCwd(path);
    return cwd ? { kind: 'cwd', cwd } : null;
  }
  return null;
}

/**
 * Incremental OSC scanner for the marks above. Output arrives in arbitrary
 * chunks, so a sequence may straddle them; only the bytes of an OPEN OSC are
 * kept, and one past SHELL_MARK_MAX_BYTES is abandoned.
 */
export function createShellMarkParser(nonce: string | null): { feed(chunk: Uint8Array): LocatedShellMark[] } {
  // 0 ground, 1 saw ESC, 2 in OSC, 3 in OSC and saw ESC, 4 ignoring a runaway OSC
  let state = 0;
  let buf: number[] = [];
  /** Bytes of the open sequence that arrived in earlier chunks. */
  let carried = 0;
  let seqStart = 0;
  const decoder = new TextDecoder('utf-8', { fatal: false });
  return {
    feed(chunk) {
      const out: LocatedShellMark[] = [];
      const finish = (end: number) => {
        const payload = decoder.decode(new Uint8Array(buf));
        const mark = interpretOscPayload(payload, nonce);
        if (mark) out.push({ mark, start: seqStart, end });
        buf = [];
        state = 0;
      };
      if (state !== 0) seqStart = -carried;
      for (let i = 0; i < chunk.length; i++) {
        const byte = chunk[i]!;
        switch (state) {
          case 0:
            if (byte === ESC) { state = 1; seqStart = i; }
            break;
          case 1:
            if (byte === 0x5d /* ] */) { state = 2; buf = []; } else if (byte === ESC) { seqStart = i; } else state = 0;
            break;
          case 2:
            if (byte === BEL) finish(i + 1);
            else if (byte === ESC) state = 3;
            else if (buf.length < SHELL_MARK_MAX_BYTES) buf.push(byte);
            else { state = 4; buf = []; }
            break;
          case 3:
            if (byte === 0x5c /* \ */) finish(i + 1);
            else if (byte === 0x5d) { state = 2; buf = []; seqStart = i - 1; } // ESC ] again: a new OSC
            else { state = byte === ESC ? 1 : 0; buf = []; if (byte === ESC) seqStart = i; }
            break;
          case 4:
            if (byte === BEL) state = 0;
            else if (byte === ESC) { state = 1; seqStart = i; }
            break;
        }
      }
      // What of an open sequence is in THIS chunk counts toward the next chunk's negative start.
      carried = state === 0 || state === 4 ? 0 : (seqStart >= 0 ? chunk.length - seqStart : carried + chunk.length);
      return out;
    },
  };
}
